### ISSUE TITLE
'"filename.tar": no parent' when filename is in associative array

### ISSUE THREAD

**Issue by takusuman** [ksh93/ksh#736] opened 2024-03-31 16:59 UTC
G'day and happy Easter, KornShell 93 developers.

I'm trying to write a script that reads a file containing information about other files to be unpacked by ``tar`` and I'm getting this error since I started to store the information in an associative array instead of ``eval``uating the values straight inside the script.
The same sort of error is described [here, on the UNIX/Linux StackExchange](https://unix.stackexchange.com/questions/430675/ksh-script-no-parent-error), but the error in question was because he/she wasn't using the correct operator.

Is there any way to workaround this?

**Comment by takusuman** [comment] 2024-03-31 17:21
<details open>

<summary>In case you wondering, here is part of my log with <tt>set -x</tt> being sprinkled over the script:</sumary>

<pre>
+ tee /dsk/0/build.log.x86-64
+ printerr '%s: Info: Building %s for %s.\n' /home/lebleue/copacabana/build-system/internals/cmd/driver.ksh cross/mussel cross
/home/lebleue/copacabana/build-system/internals/cmd/driver.ksh: Info: Building cross/mussel for cross.
+ transmutacio cross/mussel
+ set -e
+ package=cross/mussel
+ read_pkgbuild cross/mussel
+ package=cross/mussel
+ package_name=mussel
+ category=cross
+ find /home/lebleue/copacabana/packages/cross/mussel -name pkgbuild -type f -print
+ package_recipe=/home/lebleue/copacabana/packages/cross/mussel/pkgbuild
+ printf '%s\n' /home/lebleue/copacabana/packages/cross/mussel/pkgbuild
+ sed '/#/d; /^$/d;' /dev/fd/3
+ ((1))
+ read id v
+ IFS='='
+ printf 'pconf[%s]="%s"\n' pkgbuild_dir /home/lebleue/copacabana/packages/cross/mussel/pkgbuild
pconf[pkgbuild_dir]="/home/lebleue/copacabana/packages/cross/mussel/pkgbuild"
+ ((1))
+ read id v
+ IFS='='
+ printf 'pconf[%s]="%s"\n' Name '"mussel"'
pconf[Name]=""mussel""
+ ((1))
+ read id v
+ IFS='='
+ printf 'pconf[%s]="%s"\n' Vendor '"Firas Khalil Khana"'
pconf[Vendor]=""Firas Khalil Khana""
+ ((1))
+ read id v
+ IFS='='
+ printf 'pconf[%s]="%s"\n' Description '"The shortest and fastest script to build working cross compilers targeting musl libc"'
pconf[Description]=""The shortest and fastest script to build working cross compilers targeting musl libc""
+ ((1))
+ read id v
+ IFS='='
+ printf 'pconf[%s]="%s"\n' Version '"main"'
pconf[Version]=""main""
+ ((1))
+ read id v
+ IFS='='
+ printf 'pconf[%s]="%s"\n' Archive_name '"$Version.tar.gz"'
pconf[Archive_name]=""$Version.tar.gz""
+ ((1))
+ read id v
+ IFS='='
+ break
+ OBJDIR=/dsk/0/trash/slact/cross
/home/lebleue/copacabana/build-system/internals/cmd/driver.ksh[193]: main[49]: transmutacio: line 113: main.tar.gz: no parent
Error: Failed to build cross/mussel, please check log (/dsk/0/build.log.x86-64) for more details.
</pre>

</details>

**Comment by McDutchie** [comment] 2024-03-31 20:13
> Is there any way to workaround this?

It is impossible to find out the cause of the error without seeing your code. The `set -x` log is not enough. Please post the code, at least the fragment around `transmutacio: line 113`.

**Comment by McDutchie** [comment] 2024-03-31 20:15
One possibility is that you may actually be assigning to an indexed array even if you think you're assigning to an associative array. Make sure all associative arrays have been declared as such using `typeset -A`.

**Comment by takusuman** [comment] 2024-03-31 20:18
> > Is there any way to workaround this?
> 
> It is impossible to find out the cause of the error without seeing your code. The `set -x` log is not enough. Please post the code, at least the fragment around `transmutacio: line 113`.

It basically defines a ``DESTDIR`` for GNU make:
```sh
        DESTDIR="$base_destdir/$VARIANT/${pconf['Archive_name']%.t*}"
```

**Comment by takusuman** [comment] 2024-03-31 20:20
> One possibility is that you may actually be assigning to an indexed array even if you think you're assigning to an associative array. Make sure all associative arrays have been declared as such using `typeset -A`.

This is the code that reads information at the file and declares it as an associative array:

```sh
function read_manifest {
        (sed '/#/d; /^$/d;' "$1") \
                | for ((;;)); do
                if IFS='=' read id v; then
                        printf 'pconf['%s']="%s"\n' "$id" "$v"
                else
                        break
                fi
        done
}
```

**Comment by McDutchie** [comment] 2024-03-31 20:48
> This is the code that reads information at the file and declares it as an associative array:

It does not, though. An associative array is declared like `typeset -A pconf`.

**Closed as completed** 2024-03-31 20:49 UTC
Labels: invalid
