### ISSUE TITLE
$RANDOM does not get re-seeded within a subshell that redirects stdout

### ISSUE THREAD

**Issue by davidricardo** [ksh93/ksh#285] opened 2021-04-23 21:04 UTC
The ksh man page says RANDOM variable is supposed to return "a random integer, uniformly distributed between 0 and 32767" each time it's referenced. However, if the value of $RANDOM is used in a subshell that previously redirected the stdout of any command, $RANDOM has the same value if it's read multiple times within the same command. Here's an example of the bizarre behavior.
```
$ ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01
$ function rand {
>  print "this redirect should not matter" >/dev/null
>  print $RANDOM
> }
# It returns the same value every time within the loop,
$ for i in {1..3}; do x=$(rand); print $x; done
16720
16720
16720
# but a different value in each loop.
$ for i in {1..3}; do x=$(rand); print $x; done
30698
30698
30698
# When called outside the subshell, each value is different, as expected.
$ for i in {1..3}; do rand; done 
4135
21706
5128
# Without the redirect, it works as intended.
$ function rand_without_redirect { 
> print $RANDOM
}
$ for i in {1..3}; do x=$(rand_without_redirect); print $x; done
4612
23899
10106
```
zsh has a similar behavior that's not quite the same. `man zshparam` says "The values of RANDOM form an intentionally-repeatable pseudo-random sequence; subshells that reference RANDOM will result in identical pseudo-random values unless the value of RANDOM is referenced or seeded in the parent shell in between subshell invocations." But this isn't zsh, and the redirection of a previous command shouldn't matter.

This random number manipulation makes $RANDOM even more cryptographically unsecure than it already was. If anyone was depending on $RANDOM for security - which they shouldn't have been - then they're in for a bad time.

**Comment by McDutchie** [comment] 2021-04-23 21:13
Issue confirmed on current 93u+m 2021-04-22.

Cryptographic security is irrelevant because there never was any. However, yes, it's a bug because the redirection causes inconsistent behaviour.

**Comment by JohnoKing** [comment] 2021-04-23 21:34
From some quick testing, I've found that this bug behaves differently in versions prior to 93t 2008-10-09. The reproducer works when using a virtual subshell in 93t 2008-10-01 and earlier; in all versions since 2002-06-28 `$RANDOM` isn't re-seeded when used with a forked subshell. **Edit:** This is because in versions since 2008-10-09, the redirect always causes the subshell to fork.

<details open>
<summary>Reproducer script</summary>

```sh
$ cat ./random.ksh
function rand {
 print "this redirect should not matter" >/dev/null
 print $RANDOM
}

print 'Virtual subshell results:'
for ((i=0; i<3; i++)); do
	x=$(rand)
	print $x
done

print '\nForked subshell results:'
for ((i=0; i<3; i++)); do
	x=$(ulimit -t unlimited; rand)
	print $x
done

# Versions from 2008-10-01 and earlier
$ ./ksh-prior --version
  version         sh (AT&T Research) 93t 2008-10-01
$ ./ksh-prior ./random.ksh
Virtual subshell results:
208
31900
3761

Forked subshell results:
17368
17368
17368

# Versions since 2008-10-09
$ ./ksh-after --version
  version         sh (AT&T Research) 93t 2008-10-09
$ ./ksh-after ./random.ksh
Virtual subshell results:
27421
27421
27421

Forked subshell results:
27421
27421
27421
```

</details>

**Comment by hyenias** [comment] 2021-04-23 22:58
I recall seeing the RANDOM code and seeing that it does make sure it returns a different number than that of the current one. Not sure of the use case above but you could issue a `true $RANDOM` to just advance the parent $RANDOM along its pseudo-random number generator sequencing path before issuing the forked subshell (the `ulimit unlimited` forces a forked subshell instead of subshare). But as shown, the forked subshell is simply offset along the same sequencing path. See [rand](https://en.cppreference.com/w/c/numeric/random/rand).

```ksh
$ for i in {1..3}; do : $RANDOM; ( print $RANDOM $RANDOM $RANDOM ); done
29886 333 1680
11620 16401 17713
2506 23549 20031
$ for i in {1..3}; do : $RANDOM; ( ulimit unlimited; print $RANDOM $RANDOM $RANDOM) ; done
7171 9779 7967
9779 7967 27099
7967 27099 13268
```
I was surprised that _**rand**_ and _**srand**_ were not a callable math function. oh, well. Something to do to learn how to make a ksh math builtin.

**Comment by JohnoKing** [comment] 2021-04-23 23:10
After inserting some debug code into `nget_rand`, it seems the last value of the `$RANDOM` variable is always -1 when the reproducer is run. The -1 value means ksh isn't saving the old value of `$RANDOM`, so it always gets a random number with `rand`. Since the seed hasn't changed, `rand` always returns the same result.

<details open>
<summary>Debugging patch and results</summary>

```diff
--- a/src/cmd/ksh93/sh/init.c
+++ b/src/cmd/ksh93/sh/init.c
@@ -675,6 +675,7 @@ static Sfdouble_t nget_rand(register Namval_t* np, Namfun_t *fp)
 	do
 		cur = (rand()>>rand_shift)&RANDMASK;
 	while(cur==last);
+	error(ERROR_warn(0), "%ld", last);
 	*np->nvalue.lp = cur;
 	return((Sfdouble_t)cur);
 }
```
```sh
$ arch/*/bin/ksh ./random.ksh
Virtual subshell results:
./random.ksh[8]: rand: line 3: warning: -1
6945
./random.ksh[8]: rand: line 3: warning: -1
6945
./random.ksh[8]: rand: line 3: warning: -1
6945

Forked subshell results:
./random.ksh[14]: rand: line 3: warning: -1
6945
./random.ksh[14]: rand: line 3: warning: -1
6945
./random.ksh[14]: rand: line 3: warning: -1
6945
```

</details>

The patch below avoids this issue by getting the current random number while creating a subshell. This doesn't re-seed with `srand`, but rather forces `nget_rand` to obtain the next random number not equal to the one from `nv_getval`. Feel free to test the patch.

<details open>
<summary>get-random-num.patch</summary>

```diff
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -641,6 +641,7 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 		shp->cpid = 0;
 		sh_sigreset(0);
 	}
+	nv_getval(RANDNOD);
 	jmpval = sigsetjmp(buff.buff,0);
 	if(jmpval==0)
 	{
```
```sh
$ arch/*/bin/ksh ./random.ksh
Virtual subshell results:
8225
6462
8323

Forked subshell results:
6364
1570
21361
```

</details>

**Comment by hyenias** [comment] 2021-04-23 23:51
Is that -1 a result of put_rand()? Interesting... Seems you can assign a value to RANDOM and that value will be used as the seed into srand().
https://github.com/ksh93/ksh/blob/086d504393f3edc528013ab117376168498f926a/src/cmd/ksh93/sh/init.c#L645-L665

**Comment by McDutchie** [comment] 2021-04-25 16:58
`RANDOM` is actually reproducible, and meant to be such: if you seed it with the same value, you get the same sequence of values, although which ones depends on the OS. On my Mac:
```
$ ksh -c 'for((i=0;i<5;i++));do RANDOM=1; echo $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM; done'
2100 18270 30107 8581 14064
2100 18270 30107 8581 14064
2100 18270 30107 8581 14064
2100 18270 30107 8581 14064
2100 18270 30107 8581 14064
```

This bug is caused by expanding `$RANDOM` in a subshell that has forked. So it's actually logical and not really a bug. Because `$RANDOM` is reproducible, it is expected that repeatedly forking a subshell from the mainshell will repeatedly get you the same value.

If you look at it from another perspective, the real bug is really another non-forking subshell leak: virtual subshells do not act identically to forked subshells in that the progression in the `RANDOM` sequence survives a virtual subshell.

**Comment by JohnoKing** [comment] 2021-04-25 17:07
> `RANDOM` is actually reproducible, and meant to be such

I realized this a little while ago and am currently working on a proper the bugfix (since non-forking subshells should behave the same as forking subshells). Since there's not much of a point to the changes in #286, I'm closing that pull request while I develop a better fix.

**Comment by McDutchie** [comment] 2021-04-25 17:28
On a mostly unrelated note, there may be no need for command substitutions to always fork when redirecting standard output for a command within them. I think this is only necessary when making a standard output redirection permanent with `exec` or `redirect`. The following diff makes that happen, and does not seem to cause any regressions.
```diff
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -1151,7 +1151,7 @@ int	sh_redirect(Shell_t *shp,struct ionod *iop, int flag)
 				errormsg(SH_DICT,ERROR_exit(1),"cannot redirect stdout inside shared-state comsub");
 				UNREACHABLE();
 			}
-			if(shp->subshell && (flag==2 || isstring))
+			if(shp->subshell && (flag==1 || flag==2))
 				sh_subfork();
 		}
 		if(shp->redir0 && fn==0 && !(iof&IOMOV))
```

**Comment by McDutchie** [comment] 2021-04-25 17:36
On a mostly unrelated note, there may be no need for subshells to always fork when redirecting standard output for a command within them. I think this is only necessary when making a standard output redirection permanent with exec or redirect within a command substitution. The following diff makes that happen, and does not seem to cause any regressions.
```diff
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -1151,7 +1151,7 @@ int	sh_redirect(Shell_t *shp,struct ionod *iop, int flag)
 				errormsg(SH_DICT,ERROR_exit(1),"cannot redirect stdout inside shared-state comsub");
 				UNREACHABLE();
 			}
-			if(shp->subshell && (flag==2 || isstring))
+			if(shp->subshell && shp->comsub && (flag==1 || flag==2))
 				sh_subfork();
 		}
 		if(shp->redir0 && fn==0 && !(iof&IOMOV))
```
*edit:* New version of this fix now applied in 090b65e79bd9e54edd2a6bfc67e3706850a5b5f9

**Comment by McDutchie** [comment] 2021-04-25 17:45
> Since there's not much of a point to the changes in #286, I'm closing that pull request while I develop a better fix.

You'd have to find a way to save the state of the pseudorandom generator used by `rand()` upon entering a virtual subshell and restore it when exiting it. I could be wrong, but I don't think that's actually possible. It might be the only way to ensure consistent behaviour is to fork the virtual subshell before expanding `$RANDOM` within it.

**Comment by JohnoKing** [comment] 2021-04-25 18:03
I myself am inclined to agree, although maybe the patch below could be made into something that works. Basically, after a virtual subshell finishes it restores the seed `$RANDOM` was set to, then calls `rand()` the number of times the main shell obtained a random number. Unfortunately, it isn't a complete fix.

<details>
<summary>subshell-random.patch (dropdown)</summary>

```diff
--- a/src/cmd/ksh93/include/shell.h
+++ b/src/cmd/ksh93/include/shell.h
@@ -184,6 +184,8 @@ struct Shell_s
 	int		inlineno;	/* line number of current input file */
 	int		exitval;	/* exit status of the command currently being run */
 	int		savexit;	/* $? == exit status of the last command executed */
+	int		rand_seed;	/* the current pseudorandom seed used by $RANDOM */
+	int		rand_progress;	/* the number of times rand_seed has been used */
 	unsigned char	trapnote;	/* set when trap/signal is pending */
 	char		shcomp;		/* set when running shcomp */
 	unsigned int	subshell;	/* set for virtual subshell */
--- a/src/cmd/ksh93/sh/init.c
+++ b/src/cmd/ksh93/sh/init.c
@@ -645,6 +645,7 @@ static Sfdouble_t nget_seconds(register Namval_t* np, Namfun_t *fp)
 static void put_rand(register Namval_t* np,const char *val,int flags,Namfun_t *fp)
 {
 	struct rand *rp = (struct rand*)fp;
+	Shell_t *shp = sh_getinterp();
 	register long n;
 	if(!val)
 	{
@@ -658,7 +659,9 @@ static void put_rand(register Namval_t* np,const char *val,int flags,Namfun_t *f
 		n = *(double*)val;
 	else
 		n = sh_arith(rp->sh,val);
-	srand((int)(n&RANDMASK));
+	shp->rand_seed = (n&RANDMASK);
+	srand(shp->rand_seed);
+	shp->rand_progress = 0;
 	rp->rand_last = -1;
 	if(!np->nvalue.lp)
 		np->nvalue.lp = &rp->rand_last;
@@ -671,10 +674,13 @@ static void put_rand(register Namval_t* np,const char *val,int flags,Namfun_t *f
 static Sfdouble_t nget_rand(register Namval_t* np, Namfun_t *fp)
 {
 	register long cur, last= *np->nvalue.lp;
+	Shell_t *shp = sh_getinterp();
 	NOT_USED(fp);
 	do
+	{
+		shp->rand_progress++;
 		cur = (rand()>>rand_shift)&RANDMASK;
-	while(cur==last);
+	} while(cur==last);
 	*np->nvalue.lp = cur;
 	return((Sfdouble_t)cur);
 }
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -99,8 +99,10 @@ static struct subshell
 	int		subdup;
 	char		subshare;
 	char		comsub;
+	int		rand_seed;	/* parent shell $RANDOM seed */
+	int		rand_progress;	/* number of times sp->rand_seed was used */
 #if _lib_fchdir
-	int		pwdfd;	/* file descriptor for PWD */
+	int		pwdfd;		/* file descriptor for PWD */
 	char		pwdclose;
 #endif /* _lib_fchdir */
 } *subshell_data;
@@ -560,6 +562,8 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 		sh_stats(STAT_COMSUB);
 	else
 		job.curpgid = 0;
+	sp->rand_seed = shp->rand_seed;
+	sp->rand_progress = shp->rand_progress;
 	sp->subshare = shp->subshare;
 	sp->comsub = shp->comsub;
 	shp->subshare = comsub==2;
@@ -712,6 +716,14 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 	if(!shp->savesig)
 		shp->savesig = -1;
 	nv_restore(sp);
+	shp->rand_seed = sp->rand_seed;
+	shp->rand_progress = sp->rand_progress;
+	srand(shp->rand_seed);
+	while(sp->rand_progress != 0)
+	{
+		sp->rand_progress--;
+		rand();
+	}
 	if(comsub)
 	{
 		/* re-enable job control */
```
```sh
# This works with the patch
$ arch/linux.i386-64/bin/ksh -c 'RANDOM=123; echo $RANDOM; (echo $RANDOM; echo $RANDOM); echo $RANDOM'
30836
29650
17550
29650

# This, however, doesn't work
$ arch/linux.i386-64/bin/ksh -c 'RANDOM=123; echo $RANDOM; (echo $RANDOM); echo $RANDOM'
30836
29650
17550
```

</details>

**Comment by JohnoKing** [comment] 2021-04-26 13:00
Here's an updated version of the `$RANDOM` patch for non-forking subshells. This one works fine with both of the virtual subshell tests, although there's probably still room for improvement.

<details open>
<summary>subshell-random.patch</summary>

```diff
--- a/src/cmd/ksh93/include/shell.h
+++ b/src/cmd/ksh93/include/shell.h
@@ -185,6 +185,8 @@ struct Shell_s
 	int		inlineno;	/* line number of current input file */
 	int		exitval;	/* exit status of the command currently being run */
 	int		savexit;	/* $? == exit status of the last command executed */
+	int		rand_seed;	/* the current pseudorandom seed used by $RANDOM */
+	int		rand_progress;	/* the number of times rand_seed has been used */
 	unsigned char	trapnote;	/* set when trap/signal is pending */
 	char		shcomp;		/* set when running shcomp */
 	unsigned int	subshell;	/* set for virtual subshell */
@@ -204,6 +206,14 @@ typedef struct Libcomp_s
 } Libcomp_t;
 extern Libcomp_t *liblist;
 
+/* used for $RANDOM */
+struct rand
+{
+	Namfun_t	hdr;
+	Shell_t		*sh;
+	int32_t		rand_last;
+};
+
 /* flags for sh_parse */
 #define SH_NL		1	/* Treat new-lines as ; */
 #define SH_EOF		2	/* EOF causes syntax error */
--- a/src/cmd/ksh93/sh/init.c
+++ b/src/cmd/ksh93/sh/init.c
@@ -142,13 +142,6 @@ struct seconds
 	Shell_t		*sh;
 };
 
-struct rand
-{
-	Namfun_t	hdr;
-	Shell_t		*sh;
-	int32_t		rand_last;
-};
-
 struct ifs
 {
 	Namfun_t	hdr;
@@ -659,7 +652,9 @@ static void put_rand(register Namval_t* np,const char *val,int flags,Namfun_t *f
 		n = *(double*)val;
 	else
 		n = sh_arith(rp->sh,val);
-	srand((int)(n&RANDMASK));
+	rp->sh->rand_seed = (n&RANDMASK);
+	srand(rp->sh->rand_seed);
+	rp->sh->rand_progress = 0;
 	rp->rand_last = -1;
 	if(!np->nvalue.lp)
 		np->nvalue.lp = &rp->rand_last;
@@ -674,8 +669,10 @@ static Sfdouble_t nget_rand(register Namval_t* np, Namfun_t *fp)
 	register long cur, last= *np->nvalue.lp;
 	NOT_USED(fp);
 	do
+	{
+		sh.rand_progress++;
 		cur = (rand()>>rand_shift)&RANDMASK;
-	while(cur==last);
+	} while(cur==last);
 	*np->nvalue.lp = cur;
 	return((Sfdouble_t)cur);
 }
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -100,8 +100,10 @@ static struct subshell
 	int		subdup;
 	char		subshare;
 	char		comsub;
+	int		rand_seed;	/* parent shell $RANDOM seed */
+	int		rand_progress;	/* number of times sp->rand_seed was used */
 #if _lib_fchdir
-	int		pwdfd;	/* file descriptor for PWD */
+	int		pwdfd;		/* file descriptor for PWD */
 	char		pwdclose;
 #endif /* _lib_fchdir */
 } *subshell_data;
@@ -629,6 +631,9 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 			/* this is needed for var=$(trap) */
 			shp->st.otrapcom = (char**)savsig;
 		}
+		/* save the current $RANDOM seed and state */
+		sp->rand_seed = shp->rand_seed;
+		sp->rand_progress = shp->rand_progress;
 		sp->cpid = shp->cpid;
 		sp->coutpipe = shp->coutpipe;
 		sp->cpipe = shp->cpipe[1];
@@ -799,6 +804,23 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 	{
 		int n;
 		shp->options = sp->options;
+		/* restore $RANDOM seed and state (if necessary) */
+		if(sp->rand_seed != shp->rand_seed || sp->rand_progress != shp->rand_progress)
+		{
+			struct rand *rp = (struct rand*)RANDNOD->nvfun;
+			shp->rand_seed = sp->rand_seed;
+			shp->rand_progress = sp->rand_progress;
+			srand(shp->rand_seed);
+			while(sp->rand_progress > 1)
+			{
+				sp->rand_progress--;
+				rand();
+			}
+			if(sp->rand_progress > 0)
+				rp->rand_last = rand();
+			else
+				rp->rand_last = -1;
+		}
 		/* Clean up subshell hash table. */
 		if(sp->strack)
 		{
```

</details>

**Comment by McDutchie** [comment] 2021-04-26 14:18
That's clever: since you can't restore the state of the pseudorandom generator, you recreate it instead.

But I see a problem with this approach: the more $RANDOM iterations have been done in the main shell, the slower a subshell is going to be, as it has to redo at least that many `rand()` calls. Even though a `rand()` call is very fast, at some point you'll reach the point where forking is faster.

Here is a test on my system with subshells after 100 million $RANDOM iterations in the main shell. 
```sh
print "Moment..." >&2
integer i
for ((i=0; i<1000000; i++))
do	: $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM \
	$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM \
	$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM \
	$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM \
	$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM \
	$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM \
	$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM \
	$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM \
	$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM \
	$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM
done
print "Timing virtual subshells with \$RANDOM..." >&2
TIMEFORMAT=$'real\t%3lR'
time (: $RANDOM)
time (true $RANDOM)
print
print "Timing forked subshells with \$RANDOM..." >&2
time (ulimit -t unlimited; : $RANDOM)
time (ulimit -t unlimited; true $RANDOM)
```

Output:
```
$ arch/*/bin/ksh test.sh
Moment...
Timing virtual subshells with $RANDOM...
real	0m00,688s
real	0m00,737s

Timing forked subshells with $RANDOM...
real	0m00,001s
real	0m00,001s
```

IMO this is a clever idea, but possibly too clever. It introduces complexity and gradual performance degradation. I'd prefer just forking the subshell upon expanding `$RANDOM`.

**Comment by hyenias** [comment] 2021-04-26 14:53
Here is a thought. If you want more randomness in a subshell as compared to its parent, why not just reseed the subshell using `/dev/random` or `/dev/urandom`? It is still possible that the subshell RANDOM numbers might match its parent but that is what can happen. RANDOM is not unique.

**Comment by JohnoKing** [comment] 2021-04-26 14:56
Actually, maybe `rand_r` could be used to save the state of the random number generator (although it should be noted that function is deprecated). From the Linux man page:
>  Like rand(), rand_r() returns a pseudo-random integer in the range [0, RAND_MAX].  The seedp argument is a pointer to an unsigned int that is used to store state between calls.  If rand_r() is called with  the  same  initial value for the integer pointed to by seedp, and that value is not modified between calls, then the same pseudo-random sequence will result.

I have made a patch that uses `rand_r` to save the state of the pseudorandom number generator, and it seems to work. Thoughts?

<details open>
<summary>rand_r.patch</summary>

```diff
--- a/src/cmd/ksh93/include/shell.h
+++ b/src/cmd/ksh93/include/shell.h
@@ -185,6 +185,7 @@ struct Shell_s
 	int		inlineno;	/* line number of current input file */
 	int		exitval;	/* exit status of the command currently being run */
 	int		savexit;	/* $? == exit status of the last command executed */
+	unsigned int	rand_seed;	/* the current pseudorandom seed used by $RANDOM */
 	unsigned char	trapnote;	/* set when trap/signal is pending */
 	char		shcomp;		/* set when running shcomp */
 	unsigned int	subshell;	/* set for virtual subshell */
@@ -204,6 +205,14 @@ typedef struct Libcomp_s
 } Libcomp_t;
 extern Libcomp_t *liblist;
 
+/* used for $RANDOM */
+struct rand
+{
+	Namfun_t	hdr;
+	Shell_t		*sh;
+	int32_t		rand_last;
+};
+
 /* flags for sh_parse */
 #define SH_NL		1	/* Treat new-lines as ; */
 #define SH_EOF		2	/* EOF causes syntax error */
--- a/src/cmd/ksh93/sh/init.c
+++ b/src/cmd/ksh93/sh/init.c
@@ -142,13 +142,6 @@ struct seconds
 	Shell_t		*sh;
 };
 
-struct rand
-{
-	Namfun_t	hdr;
-	Shell_t		*sh;
-	int32_t		rand_last;
-};
-
 struct ifs
 {
 	Namfun_t	hdr;
@@ -659,7 +652,8 @@ static void put_rand(register Namval_t* np,const char *val,int flags,Namfun_t *f
 		n = *(double*)val;
 	else
 		n = sh_arith(rp->sh,val);
-	srand((int)(n&RANDMASK));
+	rp->sh->rand_seed = (n&RANDMASK);
+	srand(rp->sh->rand_seed);
 	rp->rand_last = -1;
 	if(!np->nvalue.lp)
 		np->nvalue.lp = &rp->rand_last;
@@ -674,7 +668,7 @@ static Sfdouble_t nget_rand(register Namval_t* np, Namfun_t *fp)
 	register long cur, last= *np->nvalue.lp;
 	NOT_USED(fp);
 	do
-		cur = (rand()>>rand_shift)&RANDMASK;
+		cur = (rand_r(&sh.rand_seed)>>rand_shift)&RANDMASK;
 	while(cur==last);
 	*np->nvalue.lp = cur;
 	return((Sfdouble_t)cur);
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -100,8 +100,10 @@ static struct subshell
 	int		subdup;
 	char		subshare;
 	char		comsub;
+	unsigned int	rand_seed;	/* parent shell $RANDOM seed */
+	int		rand_last;	/* last random number from $RANDOM in parent shell */
 #if _lib_fchdir
-	int		pwdfd;	/* file descriptor for PWD */
+	int		pwdfd;		/* file descriptor for PWD */
 	char		pwdclose;
 #endif /* _lib_fchdir */
 } *subshell_data;
@@ -511,6 +513,7 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 {
 	struct subshell sub_data;
 	register struct subshell *sp = &sub_data;
+	struct rand *rp;
 	int jmpval,isig,nsig=0,fatalerror=0,saveerrno=0;
 	unsigned int savecurenv = shp->curenv;
 	int savejobpgid = job.curpgid;
@@ -629,6 +632,10 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 			/* this is needed for var=$(trap) */
 			shp->st.otrapcom = (char**)savsig;
 		}
+		/* save the current $RANDOM seed and state */
+		rp = (struct rand*)RANDNOD->nvfun;
+		sp->rand_seed = shp->rand_seed;
+		sp->rand_last = rp->rand_last;
 		sp->cpid = shp->cpid;
 		sp->coutpipe = shp->coutpipe;
 		sp->cpipe = shp->cpipe[1];
@@ -799,6 +806,14 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 	{
 		int n;
 		shp->options = sp->options;
+		/* restore $RANDOM seed and state (if necessary) */
+		if(sp->rand_seed != shp->rand_seed)
+		{
+			rp = (struct rand*)RANDNOD->nvfun;
+			shp->rand_seed = sp->rand_seed;
+			rp->rand_last = sp->rand_last;
+			srand(shp->rand_seed);
+		}
 		/* Clean up subshell hash table. */
 		if(sp->strack)
 		{
```

</details>

**Comment by hyenias** [comment] 2021-04-26 15:05
I believe that one should not be attempting to save the state of RANDOM between the parent and subshell or adjust it. I suggest simply that it is reseeded using /dev/random or /dev/urandom assuming those exist on the system.

**Comment by McDutchie** [comment] 2021-04-26 15:08
> Here is a thought. If you want more randomness in a subshell as compared to its parent,

We actually do not, though. See [this comment](https://github.com/ksh93/ksh/issues/285#issuecomment-826355194).

**Comment by McDutchie** [comment] 2021-04-28 02:17
> I have made a patch that uses `rand_r` to save the state of the pseudorandom number generator, and it seems to work. Thoughts?

It also seems to work well on my system.

However, considering what other shells do…

```
$ bash -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
11530 29774 1426
$ bash -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
7609 1275 16255
$ bash -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
7817 29438 7695
```
bash appears to reseed $RANDOM in forked subshells; the explicit seed in the main shell has no effect.

```
$ mksh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
6962 7513 31838
$ mksh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
26655 12143 5340
$ mksh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
16948 4213 8394
```

mksh acts like bash.

```
$ yash -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
16807 16807 16807
$ zsh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
16807 16807 16807
```

yash and zsh act like ksh after the patch.

I think, though, that the bash/mksh behaviour is probably what most ksh93 users would expect. It is also how the ksh93 release versions act most of the time, even if it is by accident. The patch ensures consistent behaviour but users may think it's a bug.

So perhaps reseeding $RANDOM for forked subshells is the way to go after all.

Opinions?

**Comment by posguy99** [comment] 2021-04-28 02:25
```
$ oksh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
16807 15089 11481
$ oksh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
16807 15089 11481
$ oksh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
16807 15089 11481
```

mksh and oksh have the same ancestor (pdksh) but don't act the same... :)

```
$ pdksh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'   
16807 15089 11481
$ pdksh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
16807 15089 11481
$ pdksh -c 'RANDOM=1; echo $(echo $RANDOM) $(echo $RANDOM) $(echo $RANDOM)'
16807 15089 11481
```

oksh is obv using pdksh's algorithm.

**Comment by hyenias** [comment] 2021-04-28 10:09
I feel that forked shells should have $RANDOM reseeded. I see RANDOM as being random and should be more random. :) If I want to control that randomness then I can manually set the seed at any time to a known value. It requires more work to reseed random via `/dev/urandom` so I would prefer ksh do that easily in compiled code than making a call out to `od` to get a new seed.
```
$ ( RANDOM=1; echo $RANDOM )
2100
```
OR
``` 
$ { RANDOM=1; echo $RANDOM; }
2100
$ RANDOM=1; { echo $RANDOM; }
2100
```

**Comment by McDutchie** [comment] 2021-05-01 16:23
I apologise for going back and forth on this. This is a difficult problem.

Stepping back to analyse a bit. The following are basic premises:

1. $RANDOM is reproducible if seeded with a known seed.
2. Non-forked and forked subshells must act identically, it should not be detectable if it's forked or not.
3. By definition, a subshell is a separate environment. If expanding `$RANDOM` within a subshell influences the reproducible sequence in the parent environment, that means the subshell is leaking state into the parent environment (which is only possible if it's a non-forked/virtual subshell).
4. bash and mksh re-seed $RANDOM when initialising a subshell; zsh does not. The bash and mksh behaviour is what most users would expect.

The current ksh behaviour is inconsistent. $RANDOM does not get re-seeded when entering a subshell. But because it does not fork subshells by default, expanding $RANDOM in a subshell simply continues the main shell's sequence (which violates # 3 above). If a subshell forks for any reason, then it becomes a separate state (which violates # 2 above).

One fix I was testing is re-seeding $RANDOM if a subshell forks. That superficially makes it look like everything is fixed, but for non-forked subshells it still violates # 3, and forking would influence the sequence so # 2 is also violated. So that is not a correct fix.

@JohnoKing's [latest patch](https://github.com/ksh93/ksh/issues/285#issuecomment-826902432) fixes it for # 2 and # 3, but users will complain because of # 4 as ksh93 will start acting like zsh.

Perhaps the best fix would be @JohnoKing's patch, which implements restoring the `rand()` state for virtual subshells, with one addition: call `srand()` when initialising a virtual subshell. This would remove the need to fix anything for forked subshells as every forked subshell starts out as a virtual one. If I'm reasoning correctly this would make ksh93 act like bash and mksh regardless of forking.

**Closed as completed** 2021-05-03 03:03 UTC
Labels: bug
