### ISSUE TITLE
Build fail when compiled with 'pcc' compiler

### ISSUE THREAD

**Issue by Maselko** [ksh93/ksh#430] opened 2022-01-16 13:10 UTC
Hi,

I do not know weather you are thinking about supporting pcc compiler but as it failed, I have decided to report here. 
I am compiling on Alpine linux 3.13 x86_64 (musl libc) on WSL2, with pcc version 1.2.0.DEVEL 20211016.
The last lines of `bin/package make` were:
```
iffe: test: stat.st_fstype is an int ... no
iffe: test: stat.st_spare1 is an int ... no
iffe: test: stat.st_spare4 is an array ... no
iffe: test: stat.st_extra is an array ... no
iffe: test: stat.st_pad4 is an array ... no
+ cmp -s FEATURE/fs ast_fs.h
+ 2> /dev/null
+ rm -f ast_fs.h
+ silent test -d .
+ /bin/cp FEATURE/fs ast_fs.h
+ iffe -v -X ast -X std -c 'cc -D_BLD_DLL -fPIC -D_BLD_ast -D_AST_git_commit="8386afcd" -Os -I. -I/home/Sebastian/gits/ksh/src/lib/libast -Icomp -I/home/Sebastian/gits/ksh/src/lib/libast/comp -Iinclude -I/home/Sebastian/gits/ksh/src/lib/libast/include -Istd -I/home/Sebastian/gits/ksh/src/lib/libast/std  ' run /home/Sebastian/gits/ksh/src/lib/libast/features/fcntl.c
iffe: test: is sys/types.h a header ... yes
iffe: test: capture output of /home/Sebastian/gits/ksh/src/lib/libast/features/fcntl.c ...
./FEATURE/fs:22: error: bad #define
error: /usr/libexec/cpp terminated with status 1
iffe: test: capture output of /home/Sebastian/gits/ksh/src/lib/libast/features/fcntl.c ... cannot run
mamake [lib/libast]: *** exit code 1 making FEATURE/fcntl
mamake: *** exit code 1 making lib/libast
mamake: *** exit code 1 making all
package: make failed at Sun Jan 16 12:58:12 UTC 2022 in /home/Sebastian/gits/ksh/arch/linux.i386-64
```
If this is a bit irrelevant, sorry.

**Comment by McDutchie** [comment] 2022-01-18 01:43
Thanks for the report. I just tried building ksh on Void Linux (musl libc, lastest updates; it's got a rolling release model) with the pcc package from its repo, which is pcc 1.1.0 20141207. I do not get this build error. It fails in libsum at the performance optimizations added in ac0a3a523840fd582476f55f9601dab376dffb10 because it pretends to be gcc, though it isn't; its `__builtin_prefetch` works differently. With the patch below, which excludes pcc from this code, it builds just fine.

There's a considerable number of regression test failures when running `bin/shtests -p`. Most (?) of them seem to be due to floating point mathematics errors. pcc comes with its own libc, instead of using the OS's libc. All these failures must be the result of bugs in either the compiler or that libc, because when compiling with gcc or tcc, there are no regression test failures on this system.

```diff
diff --git a/src/lib/libsum/sum-att.c b/src/lib/libsum/sum-att.c
index 0a2ca85f..f8bfd9bb 100644
--- a/src/lib/libsum/sum-att.c
+++ b/src/lib/libsum/sum-att.c
@@ -37,9 +37,10 @@
 #define att_data	long_data
 #define att_scale	512

-#if !(defined(__clang__) && (__clang_major__ < 3 || (__clang_major__ == 3 && __clang_minor__ < 6))) && \
+#if !defined(__PCC__) && \
+	!(defined(__clang__) && (__clang_major__ < 3 || (__clang_major__ == 3 && __clang_minor__ < 6))) && \
 	(defined(__SUNPRO_C) || (defined(__GNUC__) && (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ > 0))))
-
+#warning BAD
 #if defined(__SUNPRO_C)
 #    include <sun_prefetch.h>
 #    define sum_prefetch(addr) sun_prefetch_read_many((void *)(addr))
diff --git a/src/lib/libsum/sum-crc.c b/src/lib/libsum/sum-crc.c
index 97fe30c2..efb01471 100644
--- a/src/lib/libsum/sum-crc.c
+++ b/src/lib/libsum/sum-crc.c
@@ -218,7 +218,8 @@ crc_init(Sum_t* p)
 	return 0;
 }

-#if !(defined(__clang__) && (__clang_major__ < 3 || (__clang_major__ == 3 && __clang_minor__ < 6))) && \
+#if !defined(__PCC__) && \
+	!(defined(__clang__) && (__clang_major__ < 3 || (__clang_major__ == 3 && __clang_minor__ < 6))) && \
 	(defined(__SUNPRO_C) || (defined(__GNUC__) && (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ > 0))))

 #if defined(__SUNPRO_C)
```

**Comment by McDutchie** [comment] 2022-01-18 02:13
How did you get pcc 20211016 to compile? I'm now on your exact system, Alpine linux 3.13 x86_64 (musl libc), but on VirtualBox. After `./configure --enable-native`, the build fails for me at:
```
make[2]: *** No rule to make target '../../cc2/cc2.amd64.c', needed by 'cc2'.  Stop.
```

**Comment by Maselko** [comment] 2022-01-18 08:03
So it is in Alpine package repo so I did not compile the pcc itself. However, as far as I remember, the last time I compiled pcc on the Arch linux, it failed as well. It seems like they have some error inside their makefile.

**Comment by McDutchie** [comment] 2022-02-07 03:00
I think the problem is that pcc is broken.

The Alpine package is a year old. Maybe that's the last version they could get to build. I can't get the latest cvs version to produce a usable build at all.

When using the Alpine package, the compilation fails because of an apparent preprocessor bug in pcc; it does not add newlines where it should, producing that "bad #define" error. When I add workarounds for that in the code, the compilation fails at a later point where the preprocessor just seems to output a random declaration out of nowhere that is a syntax error.

So, unfortunately this going to be a "wontfix", at least until the pcc developers can manage to produce recent code that will actually build.

For a small and very fast compiler, I recommend [tcc](https://repo.or.cz/tinycc) instead. Avoid OS release packages because they're all too old. It works well if you build the latest git code, which is very fast and simple.

**Closed as completed by McDutchie** 2022-02-07 03:00 UTC
Labels: wontfix, buildfail
