### ISSUE TITLE
First item missed in compound assignment of associative enum arrays

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#87] opened 2020-07-22 17:39 UTC
Scalar arrays (`-a`) and associative arrays (`-A`) of a type created by `enum` allow values not specified by the enum type, yielding corrupted results.

Reproducer:

```
$ enum Color_t=(red green blue orange yellow)
$ Color_t -a clr=(red blue WRONG)
$ printf '%s\n' "${clr[@]}"
red
blue
red
$ Color_t -A clr=([foo]=red [bar]=blue [bad]=WRONG)
$ printf '%s\n' "${clr[@]}"
1440
1728
2016
```
(the numbers are random, which is evidence of memory corruption)

Expected in both cases: an error message refusing to create the array due to an invalid value, as in this scalar asssignment:

```
$ Color_t clr=BAD
ksh: clr: invalid value BAD
```

This can also be reproduced in 93u+ and in ksh2020, so it doesn't look like there's an existing fix to backport.

**Comment by McDutchie** [comment] 2020-07-22 17:41
Interestingly, when repeating the assignment for an associative array, it works correctly from the second time on. From a fresh shell:
```
$ enum Color_t=(red green blue orange yellow)       
$ Color_t -A clr=([foo]=red [bar]=blue [bad]=WRONG)
$ Color_t -A clr=([foo]=red [bar]=blue [bad]=WRONG)
ksh: clr: invalid value WRONG
$ Color_t -A clr=([foo]=red [bar]=blue [bad]=WRONG)
ksh: clr: invalid value WRONG
```

**Comment by JohnoKing** [comment] 2020-07-22 18:28
It looks like there is a partial fix for this issue:
https://www.mail-archive.com/ast-developers@lists.research.att.com/msg00697.html

The patch linked above was intended to fix a problem with the ksh93v- `bool` type, although from some testing I've found that it also fixes the bug shown one comment up:
```sh
$ enum Color_t=(red green blue orange yellow)
$ Color_t -A clr=([foo]=red [bar]=blue [bad]=WRONG)
arch/linux.i386-64/bin/ksh: clr: invalid value WRONG
# Error is shown on first attempt of an invalid assignment
```

**Comment by JohnoKing** [comment] 2020-07-22 18:48
Another note about the patch, but it isn't complete in the context of `bool`, since the following still isn't returning the correct output:
```sh
$ enum _Bool=(false true)
$ _Bool -A a=( [2]=true [4]=false )
$ printf "1=%q\n" "${a[@]}"
1=true
1='' # This should be `false` like in ksh93v-, not `''`
```

**Comment by McDutchie** [comment] 2021-02-01 18:38
Most of this bug should now be fixed in 5491fe9724d8b -- just one issue remaining: `"${array[@]}"` for associative enum arrays don't yield all the values, as @JohnoKing shows in the previous comment. That's not just for bools. Now to hunt for the fix in a diff between 93u+ and 93v-...

**Comment by McDutchie** [comment] 2021-02-01 22:10
Reproducer for the bug that's left:
```sh
enum Color_t=(red green blue orange yellow)
Color_t -A clr=([foo]=red [bar]=blue [bad]=green [zut]=orange [blauw]=blue [rood]=red [groen]=green [geel]=yellow)
printf '%s\n' "${clr[@]}"
```
Output:
```
green
blue
blue

yellow
green

orange
```
Empty lines where `red` should be. Looks like the first-listed item in the array is skipped.

**Comment by McDutchie** [comment] 2021-02-01 22:22
Hmm. Is that first item even assigned correctly? Adding `printf '%s\n' "${clr[foo]}"` shows another empty line, so no! This bug is not what I thought it was; the assignment itself is failing.

**Comment by McDutchie** [comment] 2021-02-13 17:05
This fails, too, printing `BUG` twice. It works on ksh2020.
```sh
enum Enum_t=(first_element second_element)
Enum_t -A testarray
testarray[foo]=first_element
printf '%s\n' "${testarray[foo]:-BUG}" "${testarray[@]:-BUG}"
```
If `testarray[foo]` is set to `second_element` it works. So it's a general problem with the first-declared element of enumerative types in combination with ~~associative~~ arrays.

It's not just with associative arrays. This fails identically:
```sh
enum Enum_t=(first_element second_element)
Enum_t -a testarray
testarray[3]=first_element
printf '%s\n' "${testarray[3]:-BUG}" "${testarray[@]:-BUG}"
```

**Comment by JohnoKing** [comment] 2021-04-04 00:32
After looking at this bug again I've managed to trace part of the ksh93v- bugfix (**edit:** I've traced the other relevant part of the bugfix in https://github.com/ksh93/ksh/issues/87#issuecomment-812965398, but it'll need some work):
```diff
--- a/src/cmd/ksh93/sh/array.c
+++ b/src/cmd/ksh93/sh/array.c
@@ -693,6 +693,8 @@ static void array_putval(Namval_t *np, const char *string, int flags, Namfun_t *
 #endif /* SHOPT_FIXEDARRAY */
 			np->nvalue.up = up;
 		nv_putv(np,string,flags,&ap->hdr);
+		if(nofree && !up->cp)
+			up->cp = Empty;
 #if SHOPT_FIXEDARRAY
 		if(fp = (struct fixed_array*)ap->fixed)
 		{
--- a/src/cmd/ksh93/tests/enum.sh
+++ b/src/cmd/ksh93/tests/enum.sh
@@ -75,5 +75,21 @@ got=$(set +x; redirect 2>&1; Color_t -A clr=([foo]=red [bar]=blue [bad]=BAD); pr
 (((e = $?) == 1)) && [[ $got == *"$exp" ]] || err_exit "associative enum array, unspecified value:" \
 	"expected status 1, *$(printf %q "$exp"); got status $e, $(printf %q "$got")"
 
+# ${array[@]} should yield all values for associative enum arrays
+Color_t -A Colors=(
+	[foo]=red
+	[bar]=blue
+	[bad]=green
+	[zut]=orange
+	[blauw]=blue
+	[rood]=red
+	[groen]=green
+	[geel]=yellow
+)
+exp='green blue blue red yellow green red orange'
+got=${Colors[@]}
+[[ $exp == $got ]] || err_exit "\${array[@]} doesn't yield all values for associative enum arrays" \
+	"(expected $(printf %q "$exp"); got $(printf %q "$got"))"
+
 # ======
 exit $((Errors<125?Errors:125))
```

The patch above fixes the main part of this bug, allowing the following reproducers to work:
```ksh
$ cat ./colors.sh
# https://github.com/ksh93/ksh/issues/87#issuecomment-771194255
enum Color_t=(red green blue orange yellow)
Color_t -A clr=([foo]=red [bar]=blue [bad]=green [zut]=orange [blauw]=blue [rood]=red [groen]=green [geel]=yellow)
printf '%s\n' "${clr[@]}"

$ arch/*/bin/ksh ./colors.sh
green
blue
blue
red
yellow
green
red
orange

# https://github.com/ksh93/ksh/issues/87#issuecomment-662623608
$ cat ./bools.sh
! whence -q _Bool && enum _Bool=(false true)
_Bool -A a=( [2]=true [4]=false )
printf "1=%q\n" "${a[@]}"

$ arch/*/bin/ksh ./bools.sh
1=true
1=false

# https://github.com/ksh93/ksh/issues/87#issuecomment-778646287
$ cat ./first_associative_element.sh
enum Enum_t=(first_element second_element)
Enum_t -A testarray
testarray[foo]=first_element
printf '%s\n' "${testarray[foo]:-BUG}" "${testarray[@]:-BUG}"

$ arch/*/bin/ksh ./first_associative_element.sh
first_element
first_element
```

However, there are still two remaining bugs (both of which were fixed in ksh93v- 2013-10-10-alpha, so there is more backporting to do). The example that uses an indexed array is partially fixed, but not completely:
```ksh
# https://github.com/ksh93/ksh/issues/87#issuecomment-778646287
$ cat ./first_indexed-element.sh
enum Enum_t=(first_element second_element)
Enum_t -a testarray
testarray[3]=first_element
printf '%s\n' "${testarray[3]:-BUG}" "${testarray[@]:-BUG}"

$ arch/*/bin/ksh ./first_indexed-element.sh
15266
15266
$ ksh93v-2013 ./first_indexed-element.sh
first_element
first_element
```

The second bug occurs in `source` and `shcomp`. The reproducer from https://github.com/ksh93/ksh/issues/87#issuecomment-771194255 throws a syntax error when compiled with `shcomp` or run with `source`:
```sh
# https://github.com/ksh93/ksh/issues/87#issuecomment-771194255
$ cat ./colors.sh
enum Color_t=(red green blue orange yellow)
Color_t -A clr=([foo]=red [bar]=blue [bad]=green [zut]=orange [blauw]=blue [rood]=red [groen]=green [geel]=yellow)
printf '%s\n' "${clr[@]}"

$ arch/*/bin/ksh
$ source ./colors.sh
arch/linux.i386-64/bin/ksh: source: syntax error: `(' unexpected
$ shcomp ./colors.sh > /tmp/result
./colors.sh: syntax error at line 2: `(' unexpected
```

**Comment by JohnoKing** [comment] 2021-04-04 03:39
I've found the ksh93v- bugfix for the indexed arrays bug, but the patch only works when applied against ksh93u+:
```diff
--- a/src/cmd/ksh93/sh/array.c
+++ b/src/cmd/ksh93/sh/array.c
@@ -694,6 +694,8 @@ static void array_putval(Namval_t *np, const char *string, int flags, Namfun_t *
 #endif /* SHOPT_FIXEDARRAY */
 			np->nvalue.up = up;
 		nv_putv(np,string,flags,&ap->hdr);
+		if(nofree && !up->cp)
+			up->cp = Empty;
 #if SHOPT_FIXEDARRAY
 		if(fp = (struct fixed_array*)ap->fixed)
 		{
--- a/src/cmd/ksh93/sh/nvtype.c
+++ b/src/cmd/ksh93/sh/nvtype.c
@@ -1323,7 +1323,7 @@ int nv_settype(Namval_t* np, Namval_t *tp, int flags)
 			nv_putsub(np,"0",ARRAY_FILL);
 			ap = nv_arrayptr(np);
 			nelem = 1;
-		
+			nv_arraysettype(np, tp, "0" ,flags);
 		}
 	}
 	else
```
If you apply the above patch to ksh93u+m it will cause a memory fault because it's incompatible with the changes made to array.c in commit 5491fe97.

**Comment by McDutchie** [comment] 2021-04-04 03:39
> After looking at this bug again I've managed to trace part of the ksh93v- bugfix:

Great news! That's some proper progress.

> The second bug occurs in `source` and `shcomp`. The reproducer from [#87 (comment)](https://github.com/ksh93/ksh/issues/87#issuecomment-771194255) throws a syntax error when compiled with `shcomp` or run with `source`:

That's an inevitable consequence of how `source` and `shcomp` work. Both parse the entire file before executing it. The `Color_t` compound assignment is a syntax error before the type is defined, i.e. before the `enum` command is executed. When using `source` or `shcomp`, that assignment is parsed before the `enum` is executed, so the syntax error is expected. You get the same issue with defining aliases. With `shcomp` this is fundamentally unfixable. With `source` you could consider it a design flaw, but it's not something that's going to change any time soon, if ever. Wrapping it in an `eval` forces delayed parsing and works around the problem.

**Comment by JohnoKing** [comment] 2021-04-04 03:46
> That's an inevitable consequence of how source and shcomp work. Both parse the entire file before executing it. The Color_t compound assignment is a syntax error before the type is defined, i.e. before the enum command is executed. When using source or shcomp, that assignment is parsed before the enum is executed, so the syntax error is expected. You get the same issue with defining aliases. With shcomp this is fundamentally unfixable. With source you could consider it a design flaw, but it's not something that's going to change any time soon, if ever.

Well, the ksh93v- and ksh2020 versions of `source` and `shcomp` don't exhibit a syntax error when reading the reproducer, so I doubt that bug is unfixable.

**Comment by McDutchie** [comment] 2021-04-04 03:53
> Well, the ksh93v- and ksh2020 versions of `source` and `shcomp` don't exhibit a syntax error when reading the reproducer, so I doubt that bug is unfixable.

You're right.

Looks like they hacked the parser to always accept compound assignments with parentheses, whether the type is defined or not. You can comment out the `enum` command and a syntax error is still not generated. This applies even if you simply run the file without sourcing it.

**Comment by McDutchie** [comment] 2021-04-04 03:56
The parser hack in 93v- and ksh2020 causes other breakage, e.g.:

```
$ ksh-2020.0.1 -c 'echo hi bar=(baz quux)'
hi bar
```

I guess we need to decide what kind of breakage we prefer. At this point I'm not at all sure that this is a good idea. The above should absolutely be a syntax error.

**Comment by JohnoKing** [comment] 2021-04-04 03:59
I personally would rather not backport the parser hack if it's going to cause regressions.

**Comment by JohnoKing** [comment] 2021-04-04 05:02
I've fixed the crash that occurs when applying the ksh93v- indexed arrays bugfix to ksh93u+m. The memory fault happens here:
https://github.com/ksh93/ksh/blob/ca2443b58c35653986a66251b3fdc2dd63ed7864/src/cmd/ksh93/sh/array.c#L423-L424
When running the [reproducer for indexed arrays](https://github.com/ksh93/ksh/issues/87#issuecomment-778646287), `nv_getval` will return a null pointer. This also happens in the ksh93v- code [here](https://github.com/att/ast/blob/2f2b1b8be315df029ce83c2ccc12a16fdcf73f29/src/cmd/ksh93/sh/array.c#L448-L451):
```C
		if(!nv_isattr(tp,NV_BINARY))
		{
			sfprintf(shp->strbuf,"%s=%s",nv_name(nq),nv_getval(np));
			av[0] = strdup(sfstruse(shp->strbuf));
		}
```
Despite being passed a null pointer, `sfprintf` ignores it and thus avoids crashing. ksh93u+m uses `stkcopy` instead, which cannot handle null pointers (causing the memory fault). The patch below fixes the crash by making sure the pointer passed to `stkcopy` isn't null. The new patch should be an adequate fix for this issue (this doesn't fix the syntax error, but that isn't feasible without introducing regressions):
```diff
--- a/src/cmd/ksh93/sh/array.c
+++ b/src/cmd/ksh93/sh/array.c
@@ -422,12 +422,15 @@ int nv_arraysettype(Namval_t *np, Namval_t *tp, const char *sub, int flags)
 			_nv_unset(nq,NV_RDONLY);
 		nv_arraychild(np,nq,0);
 		if(!nv_isattr(tp,NV_BINARY))
-			saved_value = stkcopy(stkstd,nv_getval(np));
+		{
+			char *val = nv_getval(np);
+			saved_value = val ? stkcopy(stkstd,val) : NIL(char *);
+		}
 		if(!nv_clone(tp,nq,flags|NV_NOFREE))
 			return(0);
 		if(!rdonly)
 			nv_offattr(nq,NV_RDONLY);
-		if(!nv_isattr(tp,NV_BINARY))
+		if(!nv_isattr(tp,NV_BINARY) && saved_value)
 			nv_putval(nq,saved_value,0);
 		ap->nelem |= ARRAY_SCAN;
 		return(1);
@@ -694,6 +697,8 @@ static void array_putval(Namval_t *np, const char *string, int flags, Namfun_t *
 #endif /* SHOPT_FIXEDARRAY */
 			np->nvalue.up = up;
 		nv_putv(np,string,flags,&ap->hdr);
+		if(nofree && !up->cp)
+			up->cp = Empty;
 #if SHOPT_FIXEDARRAY
 		if(fp = (struct fixed_array*)ap->fixed)
 		{
--- a/src/cmd/ksh93/sh/nvtype.c
+++ b/src/cmd/ksh93/sh/nvtype.c
@@ -1323,7 +1323,7 @@ int nv_settype(Namval_t* np, Namval_t *tp, int flags)
 			nv_putsub(np,"0",ARRAY_FILL);
 			ap = nv_arrayptr(np);
 			nelem = 1;
-		
+			nv_arraysettype(np, tp, "0" ,flags);
 		}
 	}
 	else
```

**Comment by McDutchie** [comment] 2021-04-04 05:28
I was just about to post a very similar patch myself. You beat me to it. :)

Since I've got it now, here's my version. It's slightly more compact.

```diff
--- a/src/cmd/ksh93/sh/array.c
+++ b/src/cmd/ksh93/sh/array.c
@@ -415,18 +415,18 @@ int nv_arraysettype(Namval_t *np, Namval_t *tp, const char *sub, int flags)
 	}
 	if(nq = nv_search(sub, ap->table, NV_ADD))
 	{
-		char		*saved_value;
+		char		*saved_value = NIL(char*), *cp;
 		int		rdonly = nv_isattr(np,NV_RDONLY);
 		if(!nq->nvfun && nq->nvalue.cp && *nq->nvalue.cp==0)
 			_nv_unset(nq,NV_RDONLY);
 		nv_arraychild(np,nq,0);
-		if(!nv_isattr(tp,NV_BINARY))
-			saved_value = stkcopy(stkstd,nv_getval(np));
+		if(!nv_isattr(tp,NV_BINARY) && (cp = nv_getval(np)))
+			saved_value = stkcopy(stkstd,cp);
 		if(!nv_clone(tp,nq,flags|NV_NOFREE))
 			return(0);
 		if(!rdonly)
 			nv_offattr(nq,NV_RDONLY);
-		if(!nv_isattr(tp,NV_BINARY))
+		if(saved_value)
 			nv_putval(nq,saved_value,0);
 		ap->nelem |= ARRAY_SCAN;
 		return(1);
@@ -693,6 +693,8 @@ static void array_putval(Namval_t *np, const char *string, int flags, Namfun_t *
 #endif /* SHOPT_FIXEDARRAY */
 			np->nvalue.up = up;
 		nv_putv(np,string,flags,&ap->hdr);
+		if(nofree && !up->cp)
+			up->cp = Empty;
 #if SHOPT_FIXEDARRAY
 		if(fp = (struct fixed_array*)ap->fixed)
 		{
diff --git a/src/cmd/ksh93/sh/nvtype.c b/src/cmd/ksh93/sh/nvtype.c
index f2ffa873..03173ba2 100644
--- a/src/cmd/ksh93/sh/nvtype.c
+++ b/src/cmd/ksh93/sh/nvtype.c
@@ -1323,7 +1323,7 @@ int nv_settype(Namval_t* np, Namval_t *tp, int flags)
 			nv_putsub(np,"0",ARRAY_FILL);
 			ap = nv_arrayptr(np);
 			nelem = 1;
-		
+			nv_arraysettype(np, tp, "0" ,flags);
 		}
 	}
 	else
```

**Comment by McDutchie** [comment] 2021-04-04 06:13
Found another related bug. Unset doesn't work properly.

Reproducer (*edit*: changed to better one):
```sh
enum Color_t=(red green blue orange yellow)
Color_t -A Colors=([foo]=red)
unset Colors
typeset -p Colors
```
Output on 93u+ and 93u+m:
```
Color_t -A Colors=()
```
It works (no output) on 93v- and ksh2020. So, one (?) more thing to track down and backport...

**Comment by McDutchie** [comment] 2021-04-04 15:46
Re `nv_arraysettype()`, I think it can be simplified even further. After my initial simplification of it, I don't believe there's actually a need to save a duplicate copy of the value at all. `nv_getval()` saves the value in string form in an sfio buffer `sh.strbuf` which is overwritten on the next `nv_getval()` call. As of 5491fe9724d8b7f76605d7621669ec08a3903cb2, only `nv_clone()` and `nv_offattr()` are called/expanded in between getting and restoring the value, and as far as I can tell neither influence `sh.strbuf`.
```diff
--- a/src/cmd/ksh93/sh/array.c
+++ b/src/cmd/ksh93/sh/array.c
@@ -415,18 +415,18 @@ int nv_arraysettype(Namval_t *np, Namval_t *tp, const char *sub, int flags)
 	}
 	if(nq = nv_search(sub, ap->table, NV_ADD))
 	{
-		char		*saved_value;
+		char		*saved_value = NIL(char*);
 		int		rdonly = nv_isattr(np,NV_RDONLY);
 		if(!nq->nvfun && nq->nvalue.cp && *nq->nvalue.cp==0)
 			_nv_unset(nq,NV_RDONLY);
 		nv_arraychild(np,nq,0);
 		if(!nv_isattr(tp,NV_BINARY))
-			saved_value = stkcopy(stkstd,nv_getval(np));
+			saved_value = nv_getval(np);
 		if(!nv_clone(tp,nq,flags|NV_NOFREE))
 			return(0);
 		if(!rdonly)
 			nv_offattr(nq,NV_RDONLY);
-		if(!nv_isattr(tp,NV_BINARY))
+		if(saved_value)
 			nv_putval(nq,saved_value,0);
 		ap->nelem |= ARRAY_SCAN;
 		return(1);
```

**Comment by JohnoKing** [comment] 2021-04-04 16:22
While hunting for the ksh93v- `unset` bugfix I've stumbled across this 93v- bug:
```sh
$ cat ./colors-print.sh
enum Color_t=(red green blue orange yellow)
Color_t -A clr=([foo]=red [bar]=blue [bad]=green [zut]=orange [blauw]=blue [rood]=red [groen]=green [geel]=yellow)
typeset -p clr

# ksh93u+m
$ ksh ./colors-print.sh
Color_t -A clr=([bad]=green [bar]=blue [blauw]=blue [foo]=red [geel]=yellow [groen]=green [rood]=red [zut]=orange)

# ksh93v- and ksh2020
$ ksh93v ./colors-print.sh
Color_t -A clr=([bad]='' [bar]='' [blauw]='' [foo]='' [geel]='' [groen]='' [rood]='' [zut]='')

# ksh93u+
$ ksh93u ./colors-print.sh
Color_t -A clr=([bad]=19920 [bar]=20128 [blauw]=20336 [foo]=20544 [geel]=20752 [groen]=20960 [rood]=21168 [zut]=21376)
```
We should take care to avoid backporting this bug.

**Comment by McDutchie** [comment] 2021-04-04 16:47
Yes, let's add a test for that.

**Comment by JohnoKing** [comment] 2021-04-04 17:37
ksh93v- uses an `NV_NOTSET` attribute to avoid the `unset` bug. I've backported part of the bugfix, but from the looks of it a better fix is necessary. The patch below introduces two regression test failures in `bin/shtests -p` and causes the [93v- bug](https://github.com/ksh93/ksh/issues/87#issuecomment-813060000) with `typeset -p`:
```diff
--- a/src/cmd/ksh93/bltins/enum.c
+++ b/src/cmd/ksh93/bltins/enum.c
@@ -157,6 +157,8 @@ static char* get_enum(register Namval_t* np, Namfun_t *fp)
 	static char buff[6];
 	struct Enum *ep = (struct Enum*)fp;
 	long n = nv_getn(np,fp);
+	if(nv_isattr(np,NV_NOTSET)==NV_NOTSET)
+		return("");
 	if(n < ep->nelem)
 		return((char*)ep->values[n]);
 	sfsprintf(buff,sizeof(buff),"%u%c",n,0);
--- a/src/cmd/ksh93/data/msg.c
+++ b/src/cmd/ksh93/data/msg.c
@@ -62,6 +62,7 @@ const char e_number[]		= "%s: bad number";
 const char e_badlocale[]	= "%s: unknown locale";
 const char e_nullset[]		= "%s: parameter null";
 const char e_notset[]		= "%s: parameter not set";
+const char e_notset2[]		= "%s[%d]: parameter not set";
 const char e_noparent[]		= "%s: no parent";
 const char e_subst[]		= "%s: bad substitution";
 const char e_create[]		= "%s: cannot create";
--- a/src/cmd/ksh93/include/name.h
+++ b/src/cmd/ksh93/include/name.h
@@ -137,6 +137,7 @@ struct Ufunction
 #define NV_NOPRINT	(NV_LTOU|NV_UTOL)	/* do not print */
 #define NV_NOALIAS	(NV_NOPRINT|NV_IMPORT)
 #define NV_NOEXPAND	NV_RJUST		/* do not expand alias */
+#define NV_NOTSET	(NV_INTEGER|NV_BINARY)
 #define NV_BLTIN	(NV_NOPRINT|NV_EXPORT)
 #define BLT_ENV		(NV_RDONLY)		/* non-stoppable,
 						 * can modify environment */
@@ -234,6 +235,7 @@ extern const char	e_optincompat2[];
 extern const char	e_subscript[];
 extern const char	e_nullset[];
 extern const char	e_notset[];
+extern const char	e_notset2[];
 extern const char	e_noparent[];
 extern const char	e_notelem[];
 extern const char	e_readonly[];
--- a/src/cmd/ksh93/sh/array.c
+++ b/src/cmd/ksh93/sh/array.c
@@ -312,6 +312,8 @@ static Namval_t *array_find(Namval_t *np,Namarr_t *arp, int flag)
 				ap->cur = 0;
 		}
 	}
+	if(nv_isattr(np,NV_NOTSET)==NV_NOTSET)
+		nv_offattr(np,NV_BINARY);
 	if(is_associative(ap))
 	{
 		mp = (Namval_t*)((*arp->fun)(np,NIL(char*),NV_ACURRENT));
@@ -391,7 +393,7 @@ static Namval_t *array_find(Namval_t *np,Namarr_t *arp, int flag)
 		}
 	}
 	np->nvalue.cp = up->cp;
-	if(!up->cp)
+	if(!up->cp && nv_isattr(np,NV_NOTSET)!=NV_NOTSET)
 	{
 			char *xp = nv_setdisc(np,"get",np,(Namfun_t*)np);
 		if(flag!=ARRAY_ASSIGN)
@@ -415,18 +417,18 @@ int nv_arraysettype(Namval_t *np, Namval_t *tp, const char *sub, int flags)
 	}
 	if(nq = nv_search(sub, ap->table, NV_ADD))
 	{
-		char		*saved_value;
+		char		*saved_value = NIL(char*);
 		int		rdonly = nv_isattr(np,NV_RDONLY);
 		if(!nq->nvfun && nq->nvalue.cp && *nq->nvalue.cp==0)
 			_nv_unset(nq,NV_RDONLY);
 		nv_arraychild(np,nq,0);
 		if(!nv_isattr(tp,NV_BINARY))
-			saved_value = stkcopy(stkstd,nv_getval(np));
+			saved_value = nv_getval(np);
 		if(!nv_clone(tp,nq,flags|NV_NOFREE))
 			return(0);
 		if(!rdonly)
 			nv_offattr(nq,NV_RDONLY);
-		if(!nv_isattr(tp,NV_BINARY))
+		if(saved_value)
 			nv_putval(nq,saved_value,0);
 		ap->nelem |= ARRAY_SCAN;
 		return(1);
@@ -693,6 +695,8 @@ static void array_putval(Namval_t *np, const char *string, int flags, Namfun_t *
 #endif /* SHOPT_FIXEDARRAY */
 			np->nvalue.up = up;
 		nv_putv(np,string,flags,&ap->hdr);
+		if(nofree && !up->cp)
+			up->cp = Empty;
 #if SHOPT_FIXEDARRAY
 		if(fp = (struct fixed_array*)ap->fixed)
 		{
@@ -1750,7 +1754,9 @@ void *nv_associative(register Namval_t *np,const char *sp,int mode)
 					nv_arraychild(np,mp,0);
 				if(sh.subshell)
 					np = sh_assignok(np,1);
-				if(!ap->header.scope || !nv_search(sp,dtvnext(ap->header.table),0))
+				if(type&NV_INTEGER)
+					nv_onattr(mp,NV_NOTSET);
+				else if(!ap->header.scope || !nv_search(sp,dtvnext(ap->header.table),0))
 					ap->header.nelem++;
 				if(nv_isnull(mp))
 				{
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -1602,6 +1602,8 @@ void nv_putval(register Namval_t *np, const char *string, int flags)
 	}
 	flags &= ~NV_NODISC;
 	nv_local=0;
+	if(nv_isattr(np,NV_NOTSET)==NV_NOTSET)
+		nv_offattr(np,NV_BINARY);
 	if(flags&(NV_NOREF|NV_NOFREE))
 	{
 		if(np->nvalue.cp && np->nvalue.cp!=sp && !nv_isattr(np,NV_NOFREE)) 
@@ -2780,6 +2782,8 @@ char *nv_getval(register Namval_t *np)
 	if(numeric)
 	{
 		Sflong_t  ll;
+		if(nv_isattr(np,NV_NOTSET) == NV_NOTSET)
+			return(NiL);
 		if(!up->cp)
 			return("0");
 		if(nv_isattr (np,NV_DOUBLE)==NV_DOUBLE)
@@ -2901,6 +2905,11 @@ Sfdouble_t nv_getnum(register Namval_t *np)
 	}
      	if(nv_isattr (np, NV_INTEGER))
 	{
+		if(sh_isoption(SH_NOUNSET) && nv_isattr(np,NV_NOTSET)==NV_NOTSET)
+		{
+			int i = nv_aindex(np);
+			errormsg(SH_DICT,ERROR_exit(1),e_notset2,nv_name(np),i);
+		}
 		up= &np->nvalue;
 		if(!up->lp || up->cp==Empty)
 			r = 0;
--- a/src/cmd/ksh93/sh/nvtype.c
+++ b/src/cmd/ksh93/sh/nvtype.c
@@ -1323,7 +1323,7 @@ int nv_settype(Namval_t* np, Namval_t *tp, int flags)
 			nv_putsub(np,"0",ARRAY_FILL);
 			ap = nv_arrayptr(np);
 			nelem = 1;
-		
+			nv_arraysettype(np, tp, "0" ,flags);
 		}
 	}
 	else

```

**Comment by JohnoKing** [comment] 2021-04-04 17:54
It looks like this is the only change needed to fix the `unset` bug. It still causes regression test failures though (but it does avoid introducing the 93v- `typeset -p` bug):
```diff
--- a/src/cmd/ksh93/sh/array.c
+++ b/src/cmd/ksh93/sh/array.c
@@ -1752,7 +1752,7 @@ void *nv_associative(register Namval_t *np,const char *sp,int mode)
 					nv_arraychild(np,mp,0);
 				if(sh.subshell)
 					np = sh_assignok(np,1);
-				if(!ap->header.scope || !nv_search(sp,dtvnext(ap->header.table),0))
+				if(!(type&NV_INTEGER) && (!ap->header.scope || !nv_search(sp,dtvnext(ap->header.table),0)))
 					ap->header.nelem++;
 				if(nv_isnull(mp))
 				{
```

**Comment by hyenias** [comment] 2021-04-04 18:25
Ah, I was going to use **(NV_INTEGER|NV_BINARY)** as a flag for a new numeric type of byte aka int_8 down the road. Oh, well.

**Comment by McDutchie** [comment] 2021-04-04 18:33
> It looks like this is the only change needed to fix the `unset` bug. It still causes regression test failures though (but it does avoid introducing the 93v- `typeset -p` bug):

A strategically inserted debug output command shows that the value of `type` is octal 046, hex 0x26, when ~~unsetting~~declaring an associative enum array (*edit:* that code is run when declaring the array, not when unsetting it). Looking at nval.h tells me that this is equal to `NV_INTEGER|NV_LTOU|NV_RJUST`. The following change fixes the unset bug for me without causing any regression test failures.
```diff
--- a/src/cmd/ksh93/sh/array.c
+++ b/src/cmd/ksh93/sh/array.c
@@ -1750,7 +1752,7 @@ void *nv_associative(register Namval_t *np,const char *sp,int mode)
 					nv_arraychild(np,mp,0);
 				if(sh.subshell)
 					np = sh_assignok(np,1);
-				if(!ap->header.scope || !nv_search(sp,dtvnext(ap->header.table),0))
+				if(type!=(NV_INTEGER|NV_LTOU|NV_RJUST) && (!ap->header.scope || !nv_search(sp,dtvnext(ap->header.table),0)))
 					ap->header.nelem++;
 				if(nv_isnull(mp))
 				{
```
Now, I have no actual idea *why* this works, and that does not sit well with me. What is the `ap->header.nelem++` increase for? What does it do? Why does avoiding it fix this bug?

**Comment by McDutchie** [comment] 2021-04-06 04:19
Hopefully we'll find out later how this actually works when all the code for variables and arrays is better understood. I have been unsuccessful at breaking the fix above, so in it goes.

**Comment by JohnoKing** [comment] 2021-04-06 04:23
I've found a potential workaround for the `shcomp` syntax error that occurs with the [colors reproducer](https://github.com/ksh93/ksh/issues/87#issuecomment-771194255). This if statement block in `shcomp` will run the `alias` command to workaround parser limitations:
https://github.com/ksh93/ksh/blob/db2b1affdfb01e7d447fd2062872c72a9f8fa693/src/cmd/ksh93/sh/shcomp.c#L151-L152
Similarly, ksh93v- runs a command with `sh_trap` to implement the `_Bool` type for use with `shcomp` ([on line 125](https://github.com/att/ast/blob/2f2b1b8be315df029ce83c2ccc12a16fdcf73f29/src/cmd/ksh93/sh/shcomp.c#L125)):
```C
	sh_trap(shp,"enum _Bool=(false true) ;",0);
```

My idea is to have `shcomp` run the `enum` command, like it does for `alias`. The patch below fixes the syntax error for `shcomp` (but not `source`):
```diff
--- a/src/cmd/ksh93/sh/shcomp.c
+++ b/src/cmd/ksh93/sh/shcomp.c
@@ -148,8 +148,12 @@ int main(int argc, char *argv[])
 		stakset((char*)0,0);
 		if(t = (Shnode_t*)sh_parse(shp,in,0))
 		{
-			if((t->tre.tretyp&(COMMSK|COMSCAN))==0 && t->com.comnamp && strcmp(nv_name((Namval_t*)t->com.comnamp),"alias")==0)
-				sh_exec(t,0);
+			if((t->tre.tretyp&(COMMSK|COMSCAN))==0 && t->com.comnamp)
+			{
+				char *cmd = nv_name((Namval_t*)t->com.comnamp);
+				if(strcmp(cmd,"alias")==0 || strcmp(cmd,"enum")==0)
+					sh_exec(t,0);
+			}
 			if(!dflag && sh_tdump(out,t) < 0)
 			{
 				errormsg(SH_DICT,ERROR_exit(1),"dump failed");
```

**Comment by McDutchie** [comment] 2021-04-06 04:43
Wow. Nice find. A rather hackish solution, though. It would fail if aliases/enum types are defined based on values generated by commands executed earlier if the script is run normally, or if they are defined in a function that may or may not be run based on a certain condition. But since it already does that for aliases, why not. The basic problem is the same as both are commands that affect how the script is parsed, so the same approach should be just as good (or just as bad).

`typeset -T` will also define type commands, so could that be included as well? It would be more complicated as it depends on the option.

I think this needs some more thought. It's also more of an enhancement than a bugfix. I'd like to commit the fixes for the actual bugs and close this issue now, as it's large enough. Can we deal with the shcomp changes in a separate issue or PR?

**Comment by JohnoKing** [comment] 2021-04-06 04:50
Sounds like a good idea. I've already found breakage caused by the workaround for `alias`. If a script runs `alias -p`, the resulting `shcomp` output becomes unusable:
```sh
$ cat ./alias-p.sh
alias foo=bar
alias -p
echo foo
$ ksh <(shcomp ./alias-p.sh)  # No output
$ ksh ./alias-p.sh
alias foo=bar
foo
```

**Closed as completed** 2021-04-06 05:35 UTC
Labels: bug
