### ISSUE TITLE
Shell quoting within bracket expressions in glob patterns has no effect

### ISSUE THREAD

**Issue by McDutchie** [ksh93/ksh#488] opened 2022-07-18 14:30 UTC
This bug has been in `TODO` since the start and is now transferred here. It affects the portability of POSIX shell scripting, so it has a [modernish](https://github.com/modernish/modernish) bug ID, `BUG_BRACQUOT`.

[Reproducer](https://github.com/modernish/modernish/blob/master/lib/modernish/cap/BUG_BRACQUOT.t):
```sh
case b in
( ['a-c'] | ["!"a] )
	echo BUG ;;
( [a-c] ) echo OK ;;
( * )	# Undiscovered bug with bracket pattern matching
	echo BAD ;;
esac
```

Output: `BUG`, expected: `OK`. The `-` and `!` pattern operators are quoted which should cause the shell to parse them as non-operator characters.

**Comment by McDutchie** [comment] 2022-07-18 14:37
Here are some regression tests. On ksh93, 4a, 5a, 5b and 5c are OK, the rest are all bad. (1c and 3c are expected to fail on pure POSIX shells like dash as they do not support `^` as a synonym of `!`.)
```sh
printf '1a: '
case b in
*[a'-'c]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '1b: '
case b in
*['!'N]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '1c: '
case b in
*['^'N]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac

printf '2a: '
case b in
*[a$'-'c]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '2b: '
case b in
*[$'!'N]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '2c: '
case b in
*[$'^'N]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac

printf '3a: '
case b in
*[a"-"c]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '3b: '
case b in
*["!"N]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '3c: '
case b in
*["^"N]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac

printf '4a: '
case b in
*[a\-c]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '4b: '
case b in
*[\!N]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '4c: '
case b in
*[\^N]*)
	echo BAD match ;;
*)	echo OK no match ;;
esac

printf '5a: '
p='*[a\-c]*'
case b in
$p)	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '5b: '
p='*[\!N]*'
case b in
$p)	echo BAD match ;;
*)	echo OK no match ;;
esac
printf '5c: '
p='*[\^N]*'
case b in
$p)	echo BAD match ;;
*)	echo OK no match ;;
esac

printf '6a: '
p='*[a\-c]*'
case - in
$p)	echo OK match ;;
*)	echo BAD no match ;;
esac
printf '6b: '
p='*[\!N]*'
case \! in
$p)	echo OK match ;;
*)	echo BAD no match ;;
esac
printf '6c: '
p='*[\^N]*'
case ^ in
$p)	echo OK match ;;
*)	echo BAD no match ;;
esac
```

**Comment by McDutchie** [comment] 2022-07-28 20:48
Previous discussion: https://github.com/att/ast/issues/71

Concerns were raised that fixing this bug might [break backwards compatibility](https://github.com/att/ast/issues/71#issuecomment-380046958), though fixing it would [restore compatibility with ksh88](https://www.mail-archive.com/austin-group-l@opengroup.org/msg02036.html).

So, if a fix is found, it needs to be decided whether the fix should be applied to POSIX mode only.

**Comment by JohnoKing** [comment] 2022-09-28 21:27
Perhaps the bug is in this loop:
https://github.com/ksh93/ksh/blob/d84067a00161262f492be1836fcd64f2dd9f7d67/src/cmd/ksh93/sh/xec.c#L2269-L2292

The following patch allows the reproducers to work correctly, although it introduces regression test failures related to globbing:
```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index b76bceb1b..75f0de2fb 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -2277,7 +2277,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 					}
 					else
 						s = rex->argval;
-					type = (rex->argflag&ARG_RAW);
+					type = (rex->argflag&(ARG_RAW|ARG_QUOTED));
 					if((type && strcmp(r,s)==0) ||
 						(!type && strmatch(r,s)))
 					{

```

**Comment by McDutchie** [comment] 2022-09-29 11:29
The `ARG_QUOTED` flag is set if there are quotes anywhere in an argument, but does not make a distinction between quoted and unquoted parts of the argument.

I think the following can show us where the bug happens:
```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index b76bceb1b..a94962731 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -2271,9 +2271,12 @@ int sh_exec(register const Shnode_t *t, int flags)
 					register char *s;
 					if(rex->argflag&ARG_MAC)
 					{
+error(ERROR_warn(0),"[DEBUG1] rex->argval==[%s]",rex->argval);
 						s = sh_macpat(rex,OPTIMIZE|ARG_EXP);
+error(ERROR_warn(0),"[DEBUG2] s==[%s]",s);
 						while(*s=='\\' && s[1]==0)
 							s+=2;
+error(ERROR_warn(0),"[DEBUG3] s==[%s]",s);
 					}
 					else
 						s = rex->argval;
```
With that patch, try this reproducer:
```sh
case b in
( *"x*"["!"a"-"c]"*"* )
	;;
esac
```
Output:
```
issue488.sh: line 1: warning: [DEBUG1] rex->argval==[*"x*"["!"a"-"c]"*"*]
issue488.sh: line 1: warning: [DEBUG2] s==[*x\*[!a-c]\**]
issue488.sh: line 1: warning: [DEBUG3] s==[*x\*[!a-c]\**]
```
We can observe that sh_macpat() translates the shell quotes to backslash escapes which are internally understood by the regex parser. This explains why [the tests 4a, 5a, 5b and 5c](#issuecomment-1187581234) pass -- they all use backslashess already.

The quoted `"x"` does not get a backslash after this quote removal. So only quoted glob characters get a backslash.

In the bracket pattern `["!"a"-"c]`, neither the quoted `"!"` nor the quoted `"-"` gets a backslash after quote removal. This is the bug.

So, first, we need to figure out where and how these backslashes get added, so we can amend that code to also escape a quoted `-` and `!` (and `^`) within bracket patterns. So far I've been unable to find the code that does that.

**Comment by McDutchie** [comment] 2022-09-29 11:48
By the way, given what the `sh_macpat` call does (expansion, quote removal, backslash escaping), these two lines make no sense to me: https://github.com/ksh93/ksh/blob/d84067a00161262f492be1836fcd64f2dd9f7d67/src/cmd/ksh93/sh/xec.c#L2275-L2276
In the debug output above, those lines have no effect. And how could there possibly be a situation here where `sh_macpat` generates a string consisting of a single backslash followed by a valid shell pattern after the 0 terminator? I can't see it happening. This looks like dead code to me. A `git blame` on the ast-open-history repo shows it's been there from the start, so the reasoning has been lost to history.

In my testing, removing those two lines does not cause any regression test failures in the ksh tests, the modernish tests, or [shellspec](https://shellspec.info/).

**Comment by JohnoKing** [comment] 2022-09-29 18:12
FWIW that `sh_macpat` call was changed in ksh93v- to pass an `ARG_CASE` flag. Diff:
```diff
diff --git a/src/cmd/ksh93/include/argnod.h b/src/cmd/ksh93/include/argnod.h
index 636e473ba..b24e0045b 100644
--- a/src/cmd/ksh93/include/argnod.h
+++ b/src/cmd/ksh93/include/argnod.h
@@ -122,6 +122,7 @@ struct argnod
 #define ARG_OPTIMIZE	0x200	/* try to optimize */
 #define ARG_NOGLOB	0x400	/* no file name expansion */
 #define ARG_ARRAYOK	0x1000	/* $x[sub] ==> ${x[sub]} */
+#define ARG_CASE	0x2000	/* expanding case patterns */
 
 extern struct dolnod	*sh_argcreate(char*[]);
 extern char 		*sh_argdolminus(void*);
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index 95a9f212e..3793d44ae 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -70,6 +70,7 @@ typedef struct  _mac_
 	char		arrayok;	/* $x[] ok for arrays */
 	char		subcopy;	/* set when copying subscript */
 	char		macsub;		/* set to 1 when running mac_substitute */
+	char		maccase;	/* set to 1 when expanding case pattern */
 	int		dotdot;		/* set for .. in subscript */
 	void		*nvwalk;	/* for name space walking */
 } Mac_t;
@@ -223,6 +224,7 @@ int sh_macexpand(register struct argnod *argp, struct argnod **arghead,int flag)
 	{
 		mp->split = 0;
 		mp->pattern = ((flag&ARG_EXP)!=0);
+		mp->maccase = ((flag&ARG_CASE)!=0);
 		stkseek(stkp,0);
 	}
 	else
@@ -2497,6 +2499,19 @@ static void mac_copy(register Mac_t *mp,register const char *str, register int s
 				sh.ifstable[ESCAPE] = 0;
 		}
 	}
+	else if(mp->pattern==1 && mp->maccase)
+	{
+		while(1)
+		{
+			c = 0;
+			str = cp;
+			while(size-->0 && (c= *cp++)!='\\');
+			sfwrite(stkp,str,cp-str);
+			if(c!='\\')
+				break;
+			sfputc(stkp,c);
+		}
+	}
 	else
 		sfwrite(stkp,str,size);
 }
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index b76bceb1b..184a45696 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -2271,7 +2271,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 					register char *s;
 					if(rex->argflag&ARG_MAC)
 					{
-						s = sh_macpat(rex,OPTIMIZE|ARG_EXP);
+						s = sh_macpat(rex,OPTIMIZE|ARG_EXP|ARG_CASE);
 						while(*s=='\\' && s[1]==0)
 							s+=2;
 					}
```

Applying this change to ksh93u+m appears to fix one backslash escaping bug that caused a test failure in the yash tests:
https://github.com/siteshwar/posix-shell-tests/blob/ksh-tests/src/fnmatch.tst#L86
Relevant email from ast-users mailing list: https://marc.info/?l=ast-users&m=136562952931688&w=2
```sh
# Before fix
$ backslash=\\; case \\ in $backslash ) echo result; esac  # No output
# After fix
$ arch/*/bin/ksh
$ backslash=\\; case \\ in $backslash ) echo result; esac
result
```
Perhaps this 93v- bugfix can be expanded on.

**EDIT:** I've found that deleting the while loop following `sh_macpat` has the same effect as the 93v- patch.

**Comment by McDutchie** [comment] 2022-09-30 14:44
> So, first, we need to figure out where and how these backslashes get added, so we can amend that code to also escape a quoted `-` and `!` (and `^`) within bracket patterns. So far I've been unable to find the code that does that.

Those escapes are added in copyto() (macro.c) using `sfputc(stkp,ESCAPE)` (where `ESCAPE` is defined as a literal backslash character on line 78).

I think the fix will require keeping track of bracket expressions in that function and creating a new lexical state in the ST_DOL state table for `!`, `^` and `-`.

**Comment by McDutchie** [comment] 2022-09-30 21:15
Please try this patch. It adds special handling for `!`/`^`/`-` in bracket expressions within glob patterns that aren't EREs.
<details>
<summary>Patch version 1</summary>

```diff
diff --git a/src/cmd/ksh93/data/lexstates.c b/src/cmd/ksh93/data/lexstates.c
index ea7eb7b9c..49455c2b6 100644
--- a/src/cmd/ksh93/data/lexstates.c
+++ b/src/cmd/ksh93/data/lexstates.c
@@ -365,14 +365,14 @@ static const char sh_lexstate9[256] =
 	0,	0,	0,	0,	0,	0,	0,	0,
 	0,	0,	0,	0,	0,	0,	0,	0,
 	0,	0,	0,	0,	0,	0,	0,	0,
-	0,	0,	S_QUOTE,0,	S_DOL,	0,	S_PAT,	S_LIT,
-	S_PAT,	S_PAT,	S_PAT,	0,	S_COM,	0,	S_DOT,	S_SLASH,
+	0,	S_BRAOP,S_QUOTE,0,	S_DOL,	0,	S_PAT,	S_LIT,
+	S_PAT,	S_PAT,	S_PAT,	0,	S_COM,	S_BRAOP,S_DOT,	S_SLASH,
 	S_DIG,	S_DIG,	S_DIG,	S_DIG,	S_DIG,	S_DIG,	S_DIG,	S_DIG,
 	S_DIG,	S_DIG,	S_COLON,0,	0,	S_EQ,	0,	S_PAT,
 	0,	0,	0,	0,	0,	0,	0,	0,
 	0,	0,	0,	0,	0,	0,	0,	0,
 	0,	0,	0,	0,	0,	0,	0,	0,
-	0,	0,	0,	S_BRACT,S_ESC,	S_ENDCH,0,	0,
+	0,	0,	0,	S_BRACT,S_ESC,	S_ENDCH,S_BRAOP,0,
 	S_GRAVE,0,	0,	0,	0,	0,	0,	0,
 	0,	0,	0,	0,	0,	0,	0,	0,
 	0,	0,	0,	0,	0,	0,	0,	0,
diff --git a/src/cmd/ksh93/include/lexstates.h b/src/cmd/ksh93/include/lexstates.h
index 7910f7303..54b09a2b9 100644
--- a/src/cmd/ksh93/include/lexstates.h
+++ b/src/cmd/ksh93/include/lexstates.h
@@ -55,6 +55,7 @@
 #define S_DELIM	S_RES	/* IFS delimiter characters */
 #define S_MBYTE S_NAME	/* IFS first byte of multi-byte char */
 #define S_BLNK	36	/* space or tab */
+#define S_BRAOP	S_RES	/* potentially a glob pattern bracket expression operator (!, ^, -) */
 /* The following must be the highest numbered states */
 #define S_QUOTE	37	/* double quote character */
 #define S_GRAVE	38	/* old comsub character */
diff --git a/src/cmd/ksh93/sh/macro.c b/src/cmd/ksh93/sh/macro.c
index 95a9f212e..dfe087ad4 100644
--- a/src/cmd/ksh93/sh/macro.c
+++ b/src/cmd/ksh93/sh/macro.c
@@ -430,13 +430,14 @@ static void copyto(register Mac_t *mp,int endch, int newquote)
 	register const char	*state = sh_lexstates[ST_MACRO];
 	register char	*cp,*first;
 	Lex_t		*lp = (Lex_t*)sh.lex_context;
-	int		tilde = -1;
-	int		oldquote = mp->quote;
-	int		ansi_c = 0;
-	int		paren = 0;
-	int		ere = 0;
-	int		dotdot = 0;
-	int		brace = 0;
+	int		tilde = -1;		/* offset for tilde expansion */
+	int		dotdot = 0;		/* offset for '..' in subscript */
+	int		paren = 0;		/* level of (parentheses) */
+	int		brace = 0;		/* level of {braces} */
+	char		oldquote = mp->quote;	/* save "double quoted" state */
+	char		ansi_c = 0;		/* set when processing ANSI C escape codes */
+	char		ere = 0;		/* set when processing an extended regular expression */
+	char		bracketexpr = 0; 	/* set when in [brackets] within a non-ERE glob pattern */
 	Sfio_t		*sp = mp->sp;
 	Stk_t		*stkp = sh.stk;
 	char		*resume = 0;
@@ -530,6 +531,9 @@ static void copyto(register Mac_t *mp,int endch, int newquote)
 				n = S_PAT;
 			if(mp->pattern)
 			{
+				/* preserve \ for escaping glob pattern bracket expression operators */
+				if(bracketexpr && n==S_BRAOP)
+					break;
 				/* preserve \digit for pattern matching */
 				/* also \alpha for extended patterns */
 				if(!mp->lit && !mp->quote)
@@ -631,6 +635,8 @@ static void copyto(register Mac_t *mp,int endch, int newquote)
 				mp->pattern = c;
 			break;
 		    case S_ENDCH:
+			if(bracketexpr && cp[-1]==RBRACT)
+				bracketexpr--;
 			if((mp->lit || cp[-1]!=endch || mp->quote!=newquote))
 				goto pattern;
 			if(endch==RBRACE && mp->pattern && brace)
@@ -731,6 +737,13 @@ static void copyto(register Mac_t *mp,int endch, int newquote)
 				cp = first = fcseek(0);
 				break;
 			}
+			if(mp->pattern==1 && !ere && !bracketexpr)
+			{
+				bracketexpr++;
+				/* a ] following [, as in []abc], should not close the bracket expression */
+				if(cp[0]==RBRACT && cp[1])
+					bracketexpr++;
+			}
 			/* FALLTHROUGH */
 		    case S_PAT:
 			if(mp->pattern && !(mp->quote || mp->lit))
@@ -845,6 +858,14 @@ static void copyto(register Mac_t *mp,int endch, int newquote)
 				cp = first = fcseek(c+2);
 			}
 			break;
+		    case S_BRAOP:
+			/* escape a quoted !^- within a bracket expression */
+			if(c)
+				sfwrite(stkp,first,c);
+			first = fcseek(c);
+			if(bracketexpr && (mp->quote || mp->lit))
+				sfputc(stkp,ESCAPE);
+			break;
 		}
 	}
 done:
```
</details>

**Comment by JohnoKing** [comment] 2022-09-30 22:31
I've tested the patch and it does fix the main bug. That said, the previous backslash escaping bug I mentioned (https://github.com/ksh93/ksh/issues/488#issuecomment-1262641076) isn't fixed by the patch since it doesn't remove the extra while loop after `sh_macpat` in xec.c. Below I've left a diff to apply on top of your patch:
```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index b76bceb1b..a13de77c8 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -2270,11 +2270,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 				{
 					register char *s;
 					if(rex->argflag&ARG_MAC)
-					{
 						s = sh_macpat(rex,OPTIMIZE|ARG_EXP);
-						while(*s=='\\' && s[1]==0)
-							s+=2;
-					}
 					else
 						s = rex->argval;
 					type = (rex->argflag&ARG_RAW);
diff --git a/src/cmd/ksh93/tests/case.sh b/src/cmd/ksh93/tests/case.sh
index 10298d8d8..e39c17ccd 100755
--- a/src/cmd/ksh93/tests/case.sh
+++ b/src/cmd/ksh93/tests/case.sh
@@ -97,5 +97,35 @@ got=$(set +x; { "$SHELL" -c 'case x in [x[:bogus:]]) echo x ;; esac'; } 2>&1)
 ((!(e = $?))) && [[ -z $got ]] || err_exit 'use of invalid character class name' \
 	"(got status $e$( ((e>128)) && print -n /SIG && kill -l "$e"), $(printf %q "$got"))"
 
+# ======
+# Handling of escapes in pattern matching contexts
+# https://marc.info/?l=ast-users&m=136562952931688&w=2
+exp=no
+got=$(	x=\\x
+	if [[ x == $x ]]
+	then	echo yes
+	else	echo no
+	fi
+)
+[[ $exp == $got ]] || err_exit '[[ does not handle escapes correctly' \
+	"(expected $exp, got $(printf %q "$got"))"
+got=$(	x=\\x
+	case x in
+	$x) echo yes ;;
+	*) echo no ;;
+	esac
+)
+[[ $exp == $got ]] || err_exit 'case statements do not handle escapes correctly' \
+	"(expected $exp, got $(printf %q "$got"))"
+# https://github.com/ksh93/ksh/issues/488#issuecomment-1262641076
+exp=result
+got=$(	backslash=\\
+	case \\ in
+	$backslash)	echo result ;;
+	esac
+)
+[[ $exp == $got ]] || err_exit 'case statements do not handle escaped backslashes correctly' \
+	"(expected $exp, got $(printf %q "$got"))"
+
 # ======
 exit $((Errors<125?Errors:125))

```

**Comment by McDutchie** [comment] 2022-10-01 00:48
Thanks for the patch. I'd consider that a separate issue so I'll apply that in a separate commit.

**Comment by McDutchie** [comment] 2022-10-01 01:26
Note that the last of your regression tests (case statements do not handle escaped backslashes correctly) tests a glob pattern consisting  of a single dangling backslash, not an escaped one. The assignment `backslash=\\` assigns a single backslash after shell quoting removal.

The effect of a dangling backlash is [explicitly unspecified by POSIX](https://github.com/posix-shell-tests/posix-shell-tests/issues/4) so neither result is necessarily a bug. Having said that, currently ksh is not internally consistent as it behaves differently if a dangling backslash is preceded by another character, or when using `[[`:
```
$ bs='\'; case '\' in $bs) echo match;; *) echo no;; esac
no
$ bs='x\'; case 'x\' in $bs) echo match;; *) echo no;; esac
match
$ bs='\'; [[ '\' == $bs ]] && echo match || echo no
match
$ bs='x\'; [[ 'x\' == $bs ]] && echo match || echo no
match
```
So, the fix is good to have for consistency's sake if nothing else.

That will be number 27 on my list of bugs fixed by simply removing code.

**Comment by McDutchie** [comment] 2022-10-01 02:09
By the way, about [this comment](https://github.com/ksh93/ksh/issues/488#issuecomment-1262641076):
> FWIW that `sh_macpat` call was changed in ksh93v- to pass an `ARG_CASE` flag. Diff:

The corresponding 93v- changelog entry (from https://github.com/ksh93/ast-open-archive/commit/2ba93e7a5b048610e688cdb9bf79f076d3c8a3f4) seems to be:
```
13-04-10  A bug in which x=\\x; case x in $x) echo yes;; *) echo no; esac
	  printed yes has been fixed.  It should print no.
```
In ksh 93u+m, this already prints 'no' without that diff. And I just found that it has printed 'no' since 6a4972069fd9c338e53c6cae48be9d732e37dab4 (Jun 11, 2020) in which the [BUG_CASELIT](https://github.com/att/ast/issues/476) fix was backported from ksh2020 – which was also done purely by removing code.

So, that `ARG_CASE` patch was just to paper over that ancient breakage. Typical. In any case, this makes it very clear we do not need or want to backport it.

**Comment by McDutchie** [comment] 2022-10-01 11:51
There is still an omission in the [current patch](#issuecomment-1264030235) that shows up in pathname expansion:
```
$ arch/darwin.i386-64/bin/ksh -c 'p=[a\\-c]; set -- $p; echo $1'
b
```
That should not output `b`, as the `-` operator in the bracket expression is escaped (after the shell's backslash removal).

**Comment by McDutchie** [comment] 2022-10-01 18:54
When we apply the following debug patch to libast glob():
```diff
diff --git a/src/lib/libast/misc/glob.c b/src/lib/libast/misc/glob.c
index fcae7afd6..4c05d6a77 100644
--- a/src/lib/libast/misc/glob.c
+++ b/src/lib/libast/misc/glob.c
@@ -613,6 +613,7 @@ _ast_glob(const char* pattern, int flags, int (*errfn)(const char*, int), regist
 	int			extra = 1;
 	unsigned char		intr = 0;

+error(ERROR_warn(0),"[DEBUG] pattern==%s",pattern);
 	gp->gl_rescan = 0;
 	gp->gl_error = 0;
 	gp->gl_errfn = errfn;
```
…we can see what actually gets passed to glob():
```
$ arch/darwin.i386-64/bin/ksh -c 'p=[a\\-c]; echo "p==$p"; set -- $p; echo $1'
p==[a\-c]
arch/darwin.i386-64/bin/ksh: warning: [DEBUG] pattern==[a\\-c]
b
```
So, the backslash before the `-` is not removed, as in BUG_BRACQUOT -- instead, it's incorrectly escaped somewhere along the way, which is an opposite bug.

So this is not an omission in the [patch](https://github.com/ksh93/ksh/issues/488#issuecomment-1264030235); this is just another bug to fix separately.

**Closed as completed** 2022-10-07 02:58 UTC
Labels: bug
