### ISSUE TITLE
File descriptor is unexpectedly closed after exec in subshell

### ISSUE THREAD

**Issue by ko1nksm** [ksh93/ksh#161] opened 2021-01-23 22:36 UTC
Both 93u, 93u+m (e73696fd), and ksh2020 have this issue.

```sh
exec 9>&1

( { exec 9>&1; } 9>&- )

echo "test" >&9 # => 9: cannot open [Bad file descriptor]
```

**Comment by McDutchie** [comment] 2021-01-23 22:59
Yay, another bug with non-forking subshells, just what we needed. ;-)  Seriously though, thanks for the report. I can't make any promises about fixing it, as this type of bug is often very difficult to track down.

Also confirmed on ksh s+ 1993-12-28, so it's always been there.

**Comment by ko1nksm** [comment] 2021-01-23 23:11
No problem. It can be fixed with `ulimit -t unlimited`, which I learned from your modernish project!

```sh
exec 9>&1
( ulimit -t unlimited; { exec 9>&1; } 9>&- )
echo "test" >&9
```

**Comment by McDutchie** [comment] 2021-01-23 23:14
Yes, that's a workaround, not a fix. And it could also be a last resort to incorporate in the code -- look for `sh_subfork()` calls to see how it's done. It is usually subject to checking two flags: `shp->subshell` a.k.a. `sh.subshell` flags if we're in a virtual/non-forked subshell, `shp->subshare` a.k.a. `sh.subshare` flags if we're in a `${`shared`;}` command substitution that is technically a virtual subshell but all changes survive it.

**Comment by McDutchie** [comment] 2021-01-23 23:15
Meanwhile, I just remembered that a similar bug was fixed in db72f41f4b1331d4b3122a2e21fb93ce4f2a7c61 -- perhaps that patch can be amended to fix this bug, too, or at least provide a hint on how to fix it. The issue is that a closed file descriptor still leaks its closed state.

**Comment by JohnoKing** [comment] 2021-03-13 11:50
I've experimented with this bug a little bit and managed to create this patch (**edit:** updated with a better patch):
```diff
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -1477,7 +1477,7 @@ int	sh_redirect(Shell_t *shp,struct ionod *iop, int flag)
 					}
 					sh_iosave(shp,fn,indx,tname?fname:(trunc?Empty:0));
 				}
-				else if(sh_subsavefd(fn))
+				else if(sh_subsavefd(fn) && sh_iocheckfd(shp,fn) != IOCLOSE)
 				{
 					if(fd==fn && !shp->subshare)
 					{
```

The above patch will avoid saving the closed state of a file descriptor from a subshell unless it was explicitly closed in the preceding if statements, or when inside of a subshare. With the patch applied, the [reproducer](https://github.com/ksh93/ksh/issues/161#issue-792663981) works correctly. The patch isn't complete though, as it doesn't work when the main shell opens then closes a file descriptor:
```bash
$ cat ./open_close.sh
exec 9>&1
exec 9>&-
v=$( { exec 9>&1; } )
echo "test" >&9

$ ./open_close.sh
# No output even though there should be an error
```

**Comment by McDutchie** [comment] 2021-05-03 18:43
Thanks for that experiment. The following seems to fix it for me. For reasons I do not (yet) understand, it seems that *not* or'ing in the `IOSUBSHELL` bit flag when the file descriptor stats is `IOCLOSE` makes both @ko1nksm's and @JohnoKing's reproducers pass, with none of the other regressions tests failing. Please try to break this patch:

*edit:* It's broken. See further below.

```diff
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -1501,7 +1501,9 @@ int	sh_redirect(Shell_t *shp,struct ionod *iop, int flag)
 							sh_close(fn);
 						}
 					}
-					sh_iosave(shp,fn,indx|IOSUBSHELL,tname?fname:0);
+					sh_iosave(shp, fn,
+						sh_iocheckfd(shp,fn)==IOCLOSE ? indx : indx|IOSUBSHELL,
+						tname ? fname : 0);
 				}
 			}
 			if(fd<0)
--- a/src/cmd/ksh93/tests/io.sh
+++ b/src/cmd/ksh93/tests/io.sh
@@ -878,5 +878,22 @@ got=$(< dir1/dir2/x)
 [[ $got == "$exp" ]] || err_exit "symlink in conditional redirect wrong" \
 	"(expected $(printf %q "$exp"), got $(printf %q "$got"))"
 
+# ======
+# https://github.com/ksh93/ksh/issues/161
+: >bug161.out
+exec 9>bug161.out
+( { exec 9>&1; } 9>&- )
+echo "good" 2>/dev/null >&9
+[[ $(<bug161.out) == "good" ]] || err_exit "File descriptor is unexpectedly closed after exec in subshell" \
+	"(expected 'good', got $(printf %q "$(<bug161.out)"))"
+exec 9>/dev/null
+exec 9>&-
+v=$( { exec 9>&1; } )
+echo "test" 2>bug161.err >&9
+exp='*cannot open*'
+got=$(<bug161.err)
+[[ $got == $exp ]] || err_exit "File descriptor not properly re-closed after exec in subshell" \
+	"(expected match of $(printf %q "$exp"), got $(printf %q "$got"))"
+
 # ======
 exit $((Errors<125?Errors:125))
```

**Comment by ko1nksm** [comment] 2021-05-04 03:11
Thanks for your time. I applied the patch to d5b94a3ff8c47c746d9710d7eb4b96654ff95678 and the ShellSpec self-test failed. I managed to create a reproducible test case.

```sh
$ cat test.sh
(
  openfd() { exec 6>/tmp/fd6.txt; }
  openfd
  echo "test" >&6
)

$ cat test.sh | ~/git/ksh/arch/linux.i386-64/bin/ksh
/home/koichi/git/ksh/arch/linux.i386-64/bin/ksh[4]: 6: cannot open [Bad file descriptor]
```

**Comment by McDutchie** [comment] 2021-05-04 03:31
Thanks for the test case. The effect of the `cat test.sh | ksh`-style invocation was that the subshell (parentheses block) was not optimised out, and the subshell is needed to trigger the bug. The following reproducer should work with any kind of invocation; the subshell is never optimised out as it is not the last command.
```sh
(
  openfd() { exec 6>&1; }
  openfd
  echo "test" >&6
)
: avoid optimising out subshell
```

**Comment by McDutchie** [comment] 2021-11-09 21:03
~~I've not been successful at finding a proper fix. Here is a forking workaround that seems to do the trick. The use case is rare enough that a fork should not give a significant performance penalty.~~ It's broken.

```diff
diff --git a/src/cmd/ksh93/sh/io.c b/src/cmd/ksh93/sh/io.c
index 47fb9d63..b0d3f3cc 100644
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -1493,6 +1493,8 @@ int	sh_redirect(Shell_t *shp,struct ionod *iop, int flag)
 				}
 				else if(sh_subsavefd(fn))
 				{
+					if(shp->subshell && !shp->subshare && sh_iocheckfd(shp,fn) == IOCLOSE)
+						sh_subfork();	/* work around https://github.com/ksh93/ksh/issues/161 */
 					if(fd==fn && !shp->subshare)
 					{
 						if((r=sh_fcntl(fd,F_DUPFD,10)) > 0)
```

**Comment by McDutchie** [comment] 2022-02-10 19:45
Since we're getting nowhere finding a real fix, this somewhat overbroad workaround might need to do for the time being. Fork a virtual subshell upon encountering a permanent redirect (type==2). It seems to fix all the reproducers without causing regressions.
```diff
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1283,6 +1283,11 @@ int sh_exec(register const Shnode_t *t, int flags)
 								}
 							else
 								type = (execflg && !sh.subshell && !sh.st.trapcom[0]);
+							/*
+							 * Workaround for https://github.com/ksh93/ksh/issues/161
+							 */
+							if(type==2 && sh.subshell && !sh.subshare)
+								sh_subfork();
 							/*
 							 * A command substitution will hang on exit, writing infinite '\0', if,
 							 * within it, standard output (FD 1) is redirected for a built-in command
```

**Comment by McDutchie** [comment] 2022-02-11 00:44
But I'm not happy with having to fork each time someone uses `exec` or `redirect` to open a file descriptor within a subshell. It's a fairly common use case so the performance hit would be significant.

I think I found a way to make the need to fork much rarer. This bug only occurs when a file descriptor is closed as a result of a redirection attached to a code block. That's a rare use case, and within a subshell it's very rare, so barely anyone will notice. Redirections attached to code blocks are handled by the `TSETIO` case of `sh_exec()`: https://github.com/ksh93/ksh/blob/eabd645312ea980756ee7a147296f42e43d8cb4e/src/cmd/ksh93/sh/xec.c#L1814-L1885

So it is here that we can check for a `>&-` or `<&-` redirection and fork if we're in a virtual subshell. For that check, we need to use some of these bits: https://github.com/ksh93/ksh/blob/eabd645312ea980756ee7a147296f42e43d8cb4e/src/cmd/ksh93/include/shnodes.h#L173-L190

Here is the patch that does that. We loop through each of the attached redirections and, after `&`-ing out the `IOUFD` bits (the lower four bits which are the file descriptor number) and `IOPUT` (which is 0 for `<` and 1 for `>`), we check if the remaining value has only the `IOMOV` and `IORAW` bits set. According to my testing, forking under that condition fixes/works around the bug.
```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index 6cd54653d..933311bc7 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1821,6 +1821,22 @@ int sh_exec(register const Shnode_t *t, int flags)
 			int 	jmpval, waitall = 0;
 			int 	simple = (t->fork.forktre->tre.tretyp&COMMSK)==TCOM;
 			struct checkpt *buffp = (struct checkpt*)stkalloc(sh.stk,sizeof(struct checkpt));
+			if(sh.subshell && !sh.subshare && t->fork.forkio)
+			{
+				/* Subshell forking workaround for https://github.com/ksh93/ksh/issues/161
+				 * Check each redirection for >&- or <&-
+				 * TODO: find the elusive real fix */
+				struct ionod *i = t->fork.forkio;
+				do
+				{
+					if((i->iofile & ~(IOUFD|IOPUT)) == (IOMOV|IORAW) && !strcmp(i->ioname,"-"))
+					{
+						sh_subfork();
+						break;
+					}
+				}
+				while(i = i->ionxt);
+			}
 			sh_pushcontext(buffp,SH_JMPIO);
 			if(type&FPIN)
 			{
```

**Closed as completed** 2022-02-11 02:47 UTC
Labels: bug
