### ISSUE TITLE
echo "" | while read any_string ; ksh93  sh (AT&T Research) 93u+ 2012-08-01

### ISSUE THREAD

**Issue by Condabolid** [ksh93/ksh#204] opened 2021-03-03 00:40 UTC
For some time the while behind a pipe do not process correctly.

**first problem:**
The following  sequence I can paste  in an interactive ksh93 (x86_64) to get the problem:
```
$ echo "72700" | while read any_string
do
    echo "string=<$any_string>"
    /bin/ls -l /etc/group
    /bin/ls -l /etc/group
done
```
output:
```
string=<72700>
-rw-r--r-- 1 root root 2222 Jan 27 17:17 /etc/group
/bin/ls: /bin/ls: cannot execute [Exec format error]

```
As you can see, the first "/bin/ls" runs fine, but the second can't be executed thereafter.
Copy and using a ksh93 32bit from older System (Debian) runs fine. 

**second problem:**
The following script shows, that the execution of a complex program (ffmpeg) destroys the reading from pipe.  
```
#!/bin/ksh93
echo "72700 /tmp/blue
72701 /tmp/red
72703 /tmp/black" | while read sequence any_string
do
    echo "sequence=<$sequence>  string=<$any_string>"
    ffmpeg -i  /net/bigserv/testdata/VID-20210112-WA0000.mp4 -ss "00:00:05" -t "00:00:01" -r 1 /tmp/waste.%3d.jpg 2>/dev/null
done
```

With deactivated "ffmpeg" the output is (as expected):
```
sequence=<72700>  string=</tmp/blue>
sequence=<72701>  string=</tmp/red>
sequence=<72703>  string=</tmp/black>
```
With activated "ffmpeg" the output is:
```
sequence=<72700>  string=</tmp/blue>
sequence=</tmp/red>  string=<>
sequence=</tmp/black>  string=<>
```
It seems, that the child process (ffmpeg) influences the parent's environment. Quite impossible.

**Comment by hyenias** [comment] 2021-03-03 01:38
On your first problem listed, I was able to reproduce it with the stock ksh93u+ version of `Version AJM 93u+ 2012-08-01` from my Ubuntu 20.04 box. Good news is that your 1st issue has already been fixed via this repo's current ksh93u+m version of the KornShell. Please give it a try but be warned that ksh93u+m is still in alpha development. I have listed below a potential workaround by using a here document instead of echo with a pipe to feed that read statement.
```ksh
while read any_string
do
    echo "string=<$any_string>"
    /bin/ls -l /etc/group
    /bin/ls -l /etc/group
done <<< "72700"
```

**Comment by posguy99** [comment] 2021-03-03 01:55
Happens with `Version AJM 93u+ 2012-08-01` on a CentOS 8 box as well.

Does NOT happen with the same version on macOS Catalina 10.15.7.

Go figure.

```
[518] mbp13 $ /bin/ksh
Version AJM 93u+ 2012-08-01
[05:44 PM][ttys000 +2][~]
[519] mbp13 $ echo "72700" | while read any_string
/ls -l /etc/group
    /bin/ls -l /etc/group
done
> do
/ls -l /etc/group
    /bin/ls -l /etc/group
done
>     echo "string=<$any_string>"
/ls -l /etc/group
    /bin/ls -l /etc/group
done
>     /bin/ls -l /etc/group
>     /bin/ls -l /etc/group
> done
string=<72700>
-rw-r--r--  1 root  wheel  2922 Apr 17  2020 /etc/group
-rw-r--r--  1 root  wheel  2922 Apr 17  2020 /etc/group
[05:44 PM][ttys000 +2][~]
[520] mbp13 $ echo $KSH_VERSION
Version AJM 93u+ 2012-08-01
```

**Comment by McDutchie** [comment] 2021-03-03 02:00
The first problem was issue #79 and was fixed quite some time ago in ksh 93u+m. For now, to get 93u+m, you have to compile it yourself -- see [README.md](https://github.com/ksh93/ksh#build) for how. We will get a beta version out some time soon. (There are some embarrassing bugs left but it's just going to have to be released with them, I don't think it can wait much longer.)

The second problem is not a bug in ksh. The problem is that the `ffmpeg` command is not very well behaved. I ran into that issue myself before. `ffmpeg` reads from standard input to get keystrokes to pause and resume it, even if standard input is not connected to your keyboard. Unfortunately so does your loop. So those conflict, trying to read from the same source. You will get the same problem in any other shell. The easiest workaround is to add a `</dev/null` redirection to your `ffmpeg` command to stop it from doing that:

```sh
#!/bin/ksh93
echo "72700 /tmp/blue
72701 /tmp/red
72703 /tmp/black" | while read sequence any_string
do
    echo "sequence=<$sequence>  string=<$any_string>"
    ffmpeg -i  /net/bigserv/testdata/VID-20210112-WA0000.mp4 -ss "00:00:05" -t "00:00:01" -r 1 /tmp/waste.%3d.jpg </dev/null 2>/dev/null
done
```
If you still want your `ffmpeg` to read keyboard input as it goes, then you can use a different file descriptor for the `read` loop, let's say 3. This cannot be done with a pipe, but you can use a here-document instead:

```sh
#!/bin/ksh93
while read sequence any_string <&3
do
    echo "sequence=<$sequence>  string=<$any_string>"
    ffmpeg -i  /net/bigserv/testdata/VID-20210112-WA0000.mp4 -ss "00:00:05" -t "00:00:01" -r 1 /tmp/waste.%3d.jpg 2>/dev/null
done 3<<'EOF'
72700 /tmp/blue
72701 /tmp/red
72703 /tmp/black
EOF
```

**Comment by McDutchie** [comment] 2021-03-03 02:10
> Does NOT happen with the same version on macOS Catalina 10.15.7.

It's not 100% the same version. Apple disabled the use of `posix_spawn()` with a patch so `fork()` is always used, avoiding the bug at the cost of slower performance. The resolution of #79 is that the use of `posix_spawn()` only needs to be avoided if the shell is interactive and job control is on. See the last few comments in that issue for the details if you're interested.

**Comment by posguy99** [comment] 2021-03-03 02:14
Yea, I remember that whole thing now.

**Closed as completed** 2021-03-03 02:40 UTC
Labels: duplicate, invalid
