### ISSUE TITLE
POSIX compliance: `printf %d 010` doesn't output 8

### ISSUE THREAD

**Issue by stephane-chazelas** [ksh93/ksh#326] opened 2021-09-12 17:38 UTC
Yes, I know it's rarely ever useful for numbers with leading 0s to be treated as octal, but still POSIX requires numbers used as arguments for all the `%d`, `%u`... in `printf` to be interpreted as in the C language, so

```
printf '%d\n' 010
```

should output 8 when the `posix` option is on.

I see that with the `posix` option,  010 changes from 10 to 8 in several places (most of which unspecified by POSIX such as `let`, array indices, `[[ ... ]]`), but not in `printf`:

```
$ ksh93u+m -o posix -c 'printf "%d\n" 010'
10
```

Which just looks like an overlook.

(the `letoctal` has not effect).

See also: https://unix.stackexchange.com/a/668665

**Comment by McDutchie** [comment] 2021-09-12 19:01
I wonder if this should be fixed globally, or for POSIX mode only.

Of the other shells, only zsh outputs 10 in native mode (8 in sh emulation mode). All the rest always output 8, ~~mksh included~~ (silly me, mksh has no printf builtin so I was testing my local `/usr/bin/printf` there).

Trying out pre-93u+ ksh93 versions, it turns out older versions output 8 as expected. The bug was introduced sometime between version 2012-02-02 and 2012-02-14. That's an argument for fixing it globally.

**Comment by McDutchie** [comment] 2021-09-12 19:40
The culprit is this change from ksh93/ast-open-history@fc9d7161ad7b45090853097a7135a54476ee8573:
```diff
--- a/src/cmd/ksh93/sh/arith.c
+++ b/src/cmd/ksh93/sh/arith.c
@@ -490,7 +510,7 @@ Sfdouble_t sh_strnum(register const char *str, char** ptr, int mode)
 {
 	Shell_t	*shp = sh_getinterp();
 	register Sfdouble_t d;
-	char base=0, *last;
+	char base=(shp->inarith?0:10), *last;
 	if(*str==0)
 	{
 		if(ptr)
```

Reverting that fixes the bug with printf. It looks like the change was intentional. There's a changelog entry for it:
```
    ksh93: 12-02-07  A bug in which numbers with leading zeros could be treated as
    ksh93:    octal constants outside of ((...)) has been fixed.
```

After reverting, the following regression tests fail:
```
	arith.sh[735]: leading 0 should not be treated as octal outside ((...))
	arith.sh[737]: numbers with leading -0 should not be treated as octal outside ((...))
	variables.sh[918]: leading zeros int literal not recognized (expected '14', got '12')
```

The relevant test code: https://github.com/ksh93/ksh/blob/fba11758d724b42a136cc8d747845ef83227975f/src/cmd/ksh93/tests/arith.sh#L728-L739 https://github.com/ksh93/ksh/blob/fba11758d724b42a136cc8d747845ef83227975f/src/cmd/ksh93/tests/variables.sh#L916-L918

**Comment by avih** [comment] 2021-09-12 20:39
I can confitm your observation. All ksh93 versions I have access to print 10 (ksh93u+ - ubuntu 20.04 package) `version  sh (AT&T Research) 93u+ 2012-08-01`, ksh2020 master, and ksh93u+m - IIRC 1.0 beta).

All other shells I have access to which have builtin printf, print 8  - all ash derivatives (few dash versions, busybox ash, freebsd sh, netbsd sh), and schily tools sh (pbosh, bosh - also in posix mode).

> I wonder if this should be fixed globally, or for POSIX mode only.

Good question. It might be worth checking if this was specified in posix before or after 2012-07. If after, then I think it should definitely be global as it didn't intentionally deviate from POSIX (i.e. also not in posix mode). Otherwise, not sure, because it might suggest that it did intentionally deviate from posix. Though even on this case, globally could still be valid.

**Comment by McDutchie** [comment] 2021-09-12 20:46
Another bug with the `sh.inarith` flag introduced in ksh93/ast-open-history@fc9d7161ad7b45090853097a7135a54476ee8573: it is not reset in a command substitution used *within* an arithmetic expression. A command substitution should be a completely new context, so (given current, non-compliant printf behaviour) the following should both output `10`:

```
$ ksh -c 'printf %d\\n 010'
10
$ ksh -c 'echo $(( $(printf %d\\n 010) ))'
8
```

*edit:* Another reproducer that will still work after `printf` is fixed:
```
$ ksh -c 'integer x; x=010; echo $x'
10            # ok; it's outside ((…)) so octals should not be interpreted
$ ksh -c 'echo $(( $(integer x; x=010; echo $x) ))'
8             # bad; comsub should create new non-((…)) context, so output should still be 10
```

**Comment by McDutchie** [comment] 2021-09-12 21:05
> Another bug with the `sh.inarith` flag introduced in [ksh93/ast-open-history@fc9d716](https://github.com/ksh93/ast-open-history/commit/fc9d7161ad7b45090853097a7135a54476ee8573): it is not reset in a command substitution used _within_ an arithmetic expression.

That other bug is patched as follows:

```diff
--- a/src/cmd/ksh93/sh/subshell.c
+++ b/src/cmd/ksh93/sh/subshell.c
@@ -470,6 +470,7 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 	struct rand *rp;		/* current $RANDOM discipline function data */
 	unsigned int save_rand_seed;	/* parent shell $RANDOM seed */
 	int save_rand_last;		/* last random number from $RANDOM in parent shell */
+	char save_inarith;		/* indicates if we're currently in an arithmetic expression */
 	memset((char*)sp, 0, sizeof(*sp));
 	sfsync(shp->outpool);
 	sh_sigcheck(shp);
@@ -591,6 +592,8 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 	{
 		if(comsub)
 		{
+			save_inarith = shp->inarith;
+			shp->inarith = 0;
 			/* disable job control */
 			shp->spid = 0;
 			sp->jobcontrol = job.jobcontrol;
@@ -734,6 +737,7 @@ Sfio_t *sh_subshell(Shell_t *shp,Shnode_t *t, volatile int flags, int comsub)
 			sh_close(sp->tmpfd);
 		}
 		shp->fdstatus[1] = sp->fdstatus;
+		shp->inarith = save_inarith;
 	}
 	if(!shp->subshare)
 	{
```

**Comment by McDutchie** [comment] 2021-09-12 22:36
And this patch should fix the printf bug, without requiring the POSIX option:
```diff
--- a/src/cmd/ksh93/bltins/print.c
+++ b/src/cmd/ksh93/bltins/print.c
@@ -882,7 +882,9 @@ static int extend(Sfio_t* sp, void* v, Sffmt_t* fe)
 				}
 				break;
 			default:
+				shp->inarith = 1;	/* POSIX compliance: recognize octal constants, e.g. printf '%d\n' 010 */
 				d = sh_strnum(argp,&lastchar,0);
+				shp->inarith = 0;
 				if(d<longmin)
 				{
 					errormsg(SH_DICT,ERROR_warn(0),e_overflow,argp);
```

**Comment by hyenias** [comment] 2021-09-13 01:42
@McDutchie, I have tested your patches and they work for me.

**Comment by McDutchie** [comment] 2021-09-13 01:53
> > I wonder if this should be fixed globally, or for POSIX mode only.
> 
> Good question. It might be worth checking if this was specified in posix before or after 2012-07.

The POSIX spec, both current and the 1997 version, reference ANSI C for conversion specifiers such as `%d`, so I'm quite sure this has always been specified this way. So, it's getting fixed unconditionally. I'll add a note in `COMPATIBILITY`.

**Closed as completed** 2021-09-13 02:56 UTC
Labels: bug

**Comment by stephane-chazelas** [comment] 2021-09-13 09:04
For the record:

Before the patch:

```
$ i=010 ksh93u+m -o posix -c 'a[i]=1; printf "%d\n" i "$i" "$((i))" "$(($i))" "a[i]" "a[$i]" "a[$((i))]" "a[$(($i))]"'
10
10
10
8
1
1
1
0
```

After the patch:

```
$ i=010 ksh93u+m -o posix -c 'a[i]=1; printf "%d\n" i "$i" "$((i))" "$(($i))" "a[i]" "a[$i]" "a[$((i))]" "a[$(($i))]"'
10
8
10
8
1
0
1
0
```

It's a bit of a mess. I prefer the zsh approach where 010 is 8 in POSIX emulation and 10 otherwise.

Note that in mksh (Debian lksh build with a printf builtin), 010 is 10 in `$((...))` which changes to 8 in POSIX mode, while 010 is always 8 for printf which also makes sense to me as that `printf` takes only literal numbers, not arithmetic expressions.

**Comment by hyenias** [comment] 2021-09-13 21:38
To me it is not a mess and makes sense using ksh. I am uneducated about POSIX. From my viewpoint, ksh now will interpret more text strings as octals than before. If you use variable references or numerics then it is not interpreted as octal. Which to me is status quo as you mentioned octals for numbers are rarely used anymore. In order to keep the index lookup as octal you need to keep everything text and not turn on a numeric as ksh actually has data types whereas the other shells might just have one internal data type being text. The following script is not in POSIX mode. And yes, my shorthand descriptions probably do not make sense to anyone else but hopefully one will recognize the variable/numeric vs text difference.

Similar script:
```ksh
{
unset s a
s=010 # string repr of integer 10 or octal 8
a[s]=10 # create a sparse index array with one element using variable s
a[$(($s))]=8 # add another index to existing array using text representation of s to activate octal
typeset -p s a
printf '-------------------- printf %%d 010 testing -------------------
                   variable-to-signed-integer, s : %d
                    string-to-signed-integer, $s : %d
           string-arith-repr-of-variable, $((s)) : %d
              string-arith-repr-of-text, $(($s)) : %d
              array_variable-to-signed-int, a[s] : %d
 array_variable-from-string-to-signed-int, a[$s] : %d
  string-arith-repr-of-array_variable, a[$((s))] : %d
   string-arith-repr-of-text_element, a[$(($s))] : %d
' s "$s" "$((s))" "$(($s))" "a[s]" "a[$s]" "a[$((s))]" "a[$(($s))]"
}
```
Ouput:
```
s=010
typeset -a a=([8]=8 [10]=10)
-------------------- printf %d 010 testing -------------------
                   variable-to-signed-integer, s : 10
                    string-to-signed-integer, $s : 8
           string-arith-repr-of-variable, $((s)) : 10
              string-arith-repr-of-text, $(($s)) : 8
              array_variable-to-signed-int, a[s] : 10
 array_variable-from-string-to-signed-int, a[$s] : 8
  string-arith-repr-of-array_variable, a[$((s))] : 10
   string-arith-repr-of-text_element, a[$(($s))] : 8
$
```

**Comment by hyenias** [comment] 2021-09-13 22:31
And as a side note to other ksh users, if one wishes to work with text string octals; I would recommend encoding the base as part of the string--as in s=8#10.
```ksh
{
unset s a
s=8#10 # octal (base 8) number encoded as string
a[s]=8 # create a sparse index array with one element using variable s
typeset -p s a
printf '-------------------- printf %%d 010 testing -------------------
                   variable-to-signed-integer, s : %d
                    string-to-signed-integer, $s : %d
           string-arith-repr-of-variable, $((s)) : %d
              string-arith-repr-of-text, $(($s)) : %d
              array_variable-to-signed-int, a[s] : %d
 array_variable-from-string-to-signed-int, a[$s] : %d
  string-arith-repr-of-array_variable, a[$((s))] : %d
   string-arith-repr-of-text_element, a[$(($s))] : %d
' s "$s" "$((s))" "$(($s))" "a[s]" "a[$s]" "a[$((s))]" "a[$(($s))]"
}
```
Output:
```
s=8#10
typeset -a a=([8]=8)
-------------------- printf %d 010 testing -------------------
                   variable-to-signed-integer, s : 8
                    string-to-signed-integer, $s : 8
           string-arith-repr-of-variable, $((s)) : 8
              string-arith-repr-of-text, $(($s)) : 8
              array_variable-to-signed-int, a[s] : 8
 array_variable-from-string-to-signed-int, a[$s] : 8
  string-arith-repr-of-array_variable, a[$((s))] : 8
   string-arith-repr-of-text_element, a[$(($s))] : 8
```

**Comment by McDutchie** [comment] 2021-09-13 23:36
This is another bug:

```
$ n=010; echo $((n))                 
10
$ n=010; echo $(($n))
8
```

Both should output 8. There should be no difference between `$((n)` and `$(($n))`. This is definitely true for POSIX, but it also seems to be what the ksh developers intended, as they wanted to recognise octals within `((`…`))`. And zero other shells act like this.

So this will need a new issue opening.

**Comment by stephane-chazelas** [comment] 2021-09-14 19:05
> This is another bug:
> 
> ```
> $ n=010; echo $((n))                 
> 10
> $ n=010; echo $(($n))
> 8
> ```
> 
> Both should output 8. There should be no difference between $((n) and $(($n)). This is definitely true for POSIX, but it also seems to be what the ksh developers intended, as they wanted to recognise octals within ((…)). And zero other shells act like this.
> 
> So this will need a new issue opening.

But what about:

```
i=010
a[i]=i
(( a[i]++ ))
[ 'a[i]' -eq 11 ]
[[ a[i] -eq 11 ]]
let 'a[i] == 11'
```

Having arithmetic expressions evaluated differently depending on where they''re found is less that ideal.

Also note  POSIX requires arguments _shall be evaluated as if by
     the strtod() function if the corresponding conversion specifier is a, A, e, E, f, F, g, or G._

That means that `printf %g '8#111'` or `printf %g 8+12` are required to output 8 (and a warning message about the incomplete conversion)
