### ISSUE TITLE
Shell linter does not detect invalid array declarations

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#427] opened 2022-01-14 20:41 UTC
This bug was originally reported in https://github.com/att/ast/issues/55, and currently exists in all versions of ksh. The shell linter cannot detect invalid array declarations:

```sh
$ cat /tmp/invalid-associative-array
#!/usr/bin/ksh

typeset -A fn
fn=([foo_key]=foo_val [bar_key])
printf %s\\n ${fn[foo_key]}

$ cat /tmp/zsh-array
#!/usr/bin/zsh

typeset -A fn
fn=(foo_key foo_val bar_key bar_val)
printf %s\\n ${fn[foo_key]} ${fn[bar_key]}

$ ksh -n /tmp/invalid-associative-array; echo $?
0
$ ksh -n /tmp/zsh-array; echo $?                
0
```
Also of note is that the first reproducer will fail with a vague 'not found' error when run directly, which probably isn't the correct error message:
```sh
$ ksh /tmp/invalid-associative-array         
/tmp/invalid-associative-array[4]: [bar_key]: not found

```

**Comment by McDutchie** [comment] 2022-01-14 20:51
It tries to execute `[bar_key]` as a command. If you create a file by that name, make it executable, and put it somewhere in your `$PATH`, it will be executed.

**Comment by McDutchie** [comment] 2022-01-14 21:14
I am not sure a fix for the noexec linter is realistic. Without executing the typeset command that sets the type of the variable, it is not possible to know which is the correct syntax for an array declaration.

Trying to execute an invalid array declaration element as a command, though, is certainly a bug.

**Comment by McDutchie** [comment] 2022-01-15 15:28
The spurious command execution happens here in nv_setlist(): https://github.com/ksh93/ksh/blob/8386afcddfe8deb5daced94cb885222c2ce4e967/src/cmd/ksh93/sh/name.c#L565

**Comment by McDutchie** [comment] 2022-02-03 22:38
We can block the spurious command execution by checking if there is a command name:
```diff
--- a/src/cmd/ksh93/sh/name.c
+++ b/src/cmd/ksh93/sh/name.c
@@ -562,6 +562,11 @@ void nv_setlist(register struct argnod *arg,register int flags, Namval_t *typ)
 					L_ARGNOD->nvflag = NV_REF|NV_NOFREE;
 					L_ARGNOD->nvfun = 0;
 				}
+				if(tp->com.comarg && *tp->com.comarg->argval)
+				{
+					errormsg(SH_DICT,ERROR_exit(1),"foo");
+					UNREACHABLE();
+				}
 				sh_exec(tp,sh_isstate(SH_ERREXIT));
 #if SHOPT_TYPEDEF
 				if(sh.prefix)
```
That fixes the problem, but unfortunately causes too many regression test failures to list here, as compound assignments break – they rely on having actual commands in this context.

**Comment by McDutchie** [comment] 2022-07-05 17:47
I think this is a correct patch for the spurious command execution. It actually only happens if the erroneous word starts with `[`. The syntax error check failed to check for a subsequent `]=`.
```diff
diff --git a/src/cmd/ksh93/sh/parse.c b/src/cmd/ksh93/sh/parse.c
index 17a714218..9747b53eb 100644
--- a/src/cmd/ksh93/sh/parse.c
+++ b/src/cmd/ksh93/sh/parse.c
@@ -1507,7 +1507,7 @@ static Shnode_t *simple(Lex_t *lexp,int flag, struct ionod *io)
 			lexp->token = LBRACE;
 			break;
 		}
-		if(associative && argp->argval[0]!='[')
+		if(associative && (argp->argval[0]!='[' || !strstr(argp->argval,"]=")))
 			sh_syntax(lexp);
 		/* check for assignment argument */
 		if((argp->argflag&ARG_ASSIGN) && assignment!=2)
```
Before:
```
$ ksh -c 'typeset -A foo=([x]=1 [y])'
ksh: [y]: not found
```
After:
```
$ arch/darwin.i386-64/bin/ksh -c 'typeset -A foo=([x]=1 [y])'
arch/darwin.i386-64/bin/ksh: syntax error at line 1: `[y]' unexpected
```

**Comment by McDutchie** [comment] 2022-07-05 18:11
As for the linter: as I [wrote earlier](https://github.com/ksh93/ksh/issues/427#issuecomment-1013477538):

> Without executing the typeset command that sets the type of the variable, it is not possible to know which is the correct syntax for an array declaration.

And that is why errors such as "cannot append indexed array to associative array" are thrown at run time and not at parse time. The fundamental issue is that ksh is very much an interpreted language and not a compiled one (shcomp notwithstanding); variables are declared when their declaration commands are executed, and not at parse time.

Noexec only parses a script, line by line from start to finish, whereas execution may happen in any order due to conditionals, functions, etc. The array declaration could be conditionally executed, or variables of that type could be used on lower line numbers than their declarations even if the declaration is executed before use.

So I'm afraid a correct linter for this is not even theoretically possible. At best it would be a hack that sort of works for the most common use cases, and this shell already has too many of those. So it's a `wontfix`; sorry.

**Closed as completed** 2022-07-05 20:19 UTC
Labels: bug, enhancement, wontfix
