### ISSUE TITLE
'return' combined with '||' statement has wrong exit status

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#117] opened 2020-08-17 21:11 UTC
Running `return || true` or `return || false` in a function causes the function to return with exit status zero instead of one:
```sh
# This bug is also in ksh93n-, ksh93u+, ksh93v- and ksh2020
$ cat ./reproducer.sh
foo() {
	false
	return || true
}
foo
if [ $? = 0 ]; then
	echo 'Failure'
	exit 1
fi
exit 0
$ ksh ./reproducer.sh
Failure
$ dash ./reproducer.sh # No output when using other shells
$ 
```
I found this problem while debugging BUG_LOOPRET2, which is similar (although that bug only applies to loops, while the above reproducer doesn't use a loop):
https://github.com/ksh93/ksh/blob/d03e948bcdaa105086f7fb02a69df5f05eb9f03f/TODO#L57-L61

**Comment by JohnoKing** [comment] 2020-08-18 21:25
There is also another bug with `return` in `for` loops:
```sh
$ cat ./forloopbug.sh
# This script should print '1'
foo() {
    false
    for i in 1; do
        return
    done
}
foo
echo $?
$ ksh ./forloopbug.sh
0
```

The problem (at least for BUG_LOOPRET2 and the above `for` loop issue) seems to be that `shp->oldexit` is set to zero when it's set to the value of `shp->exitval`:
https://github.com/ksh93/ksh/blob/c3388ffd85653327b7abf875a60e38d1e14322e0/src/cmd/ksh93/sh/xec.c#L975-L976

`shp->exitval` is zero when BUG_LOOPRET2 occurs or when `return || true` is run. This causes functions to return with exit status zero instead of the previous exit status. I have a patch that fixes `return` when it's the only conditional command of a `while` or `until` loop and when it's the first command of a `for` loop, although `return || true` is still broken (as a result the [modernish tests for BUGLOOPRET2](https://github.com/modernish/modernish/blob/3ddcbd1320f16a3fe84abb31c14750c32e23743d/lib/modernish/tst/loop_cond.t#L66-L101) still fail):
```diff
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -2069,6 +2069,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 			nameref = nv_isref(np)!=0;
 			shp->st.loopcnt++;
 			cp = *args;
+			shp->exitval = shp->oldexit; /* preserve old exit status */
 			while(cp && shp->st.execbrk==0)
 			{
 				if(t->tre.tretyp&COMSCAN)
@@ -2190,6 +2191,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 			}
 #endif /*SHOPT_FILESCAN */
 			shp->st.loopcnt++;
+			shp->exitval = shp->oldexit; /* preserve old exit status */
 			while(shp->st.execbrk==0)
 			{
 #if SHOPT_FILESCAN
```
After applying the above diff, the following script now works as expected:
```sh
$ cat ./bugloopret2.sh
foo() {
    false
    while return; do
        true
    done
}
foo
echo $?

# for loop bug
bar() {
    false
    for i in 1; do
        return
    done
}
bar
echo $?
$ arch/*/bin/ksh ./bugloopret2.sh
1
1
```

**Comment by McDutchie** [comment] 2020-09-09 00:32
Thanks for working that out, it gave me an idea of where to look next.

Your diff does work to fix those cases. But as soon as you add a redirection after the `done` (such as `2>/dev/null` or `2>&1`), they both fail again. However, that can be fixed by restoring the exit status when executing a `TSETIO` (redirection):
```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index 6c620ba..aa3f23a 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1756,6 +1756,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 			int 	jmpval, waitall;
 			int 	simple = (t->fork.forktre->tre.tretyp&COMMSK)==TCOM;
 			struct checkpt *buffp = (struct checkpt*)stkalloc(shp->stk,sizeof(struct checkpt));
+			shp->exitval = shp->oldexit;
 			if(shp->subshell)
 				execflg = 0;
 			sh_pushcontext(shp,buffp,SH_JMPIO);
```
It can be fixed similarly for `return && true` and `return || true`, as follows:
```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index 6c620ba..682b36b 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -1999,6 +1999,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 		    case TAND:
 			if(type&TTEST)
 				skipexitset++;
+			shp->exitval = shp->oldexit;
 			if(sh_exec(t->lst.lstlef,OPTIMIZE)==0)
 				sh_exec(t->lst.lstrit,flags);
 			break;
@@ -2006,6 +2007,7 @@ int sh_exec(register const Shnode_t *t, int flags)
 		    case TORF:
 			if(type&TTEST)
 				skipexitset++;
+			shp->exitval = shp->oldexit;
 			if(sh_exec(t->lst.lstlef,OPTIMIZE)!=0)
 				sh_exec(t->lst.lstrit,flags);
 			break;
```

**Comment by McDutchie** [comment] 2020-09-09 01:41
A better/simpler way to fix all of these cases is probably this: instead of restoring `oldexit` in multiple places, simply don't reset `exitval` except in the cases where it's needed:
* `TCOM` (simple command – needed for a lone shell assignment to return status zero),
* ~~`TFORK` (command run in the background),~~
* `TFOR` (for/select loop) as you can have an empty `in` list meaning no command gets run but it still needs to reset the exit status, and
* `TSW` (`case`…`in`) as it's valid to have a `case` construct that doesn't run any command and it still needs to reset the exit status.

I'm pretty sure it's not needed in any other case. All the other conditional constructs and loops run at least one command, so the exit status gets reset when `TCOM` is handled.

[broken diff removed]

*edit*: my fix for `TFOR` wasn't quite correct. The exit status must be reset only if there are no loop arguments, so the loop is a no-op; otherwise, the exit status is not preserved for a `return` within the loop. Fixed now.

**Comment by McDutchie** [comment] 2020-09-09 02:09
> `TCOM` (simple command – needed for a lone shell assignment to return status zero),

Unconditionally resetting exitval for a `TCOM` is also problematic. It fails this test case, which works on every other shell:

```sh
foo() { return; }
false
foo && echo "'return' within function does not preserve exit status"
```
So this needs to be dealt with in a different way. The `TCOM` identifier deals with both actual commands and shell assignments that are not followed by any command (this is considered a null command). Since the exit status is always set if an actual command is run, we only need to reset it to zero if there is no command, so that lone shell assignments still reset the exit status to zero as they're supposed to.

*edit:* We also don't actually need the `TFORK` change now (see next comment).

Updated diff:

```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index 6c620ba..455a930 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -974,12 +974,11 @@ int sh_exec(register const Shnode_t *t, int flags)
 		type = t->tre.tretyp;
 		if(!shp->intrap)
 			shp->oldexit=shp->exitval;
-		shp->exitval=0;
 		shp->lastsig = 0;
 		shp->lastpath = 0;
 		switch(type&COMMSK)
 		{
-		    case TCOM:
+		    case TCOM:	/* simple command */
 		    {
 			register struct argnod	*argp;
 			char		*trap;
@@ -1504,6 +1503,8 @@ int sh_exec(register const Shnode_t *t, int flags)
 			else if(!io)
 			{
 			setexit:
+				if(!np)
+					shp->exitval = 0;
 				exitset();
 				break;
 			}
@@ -2044,6 +2045,8 @@ int sh_exec(register const Shnode_t *t, int flags)
 				args=sh_argbuild(shp,&argn,tp,0);
 				nargs = argn;
 			}
+			if(nargs==0)
+				shp->exitval = 0;
 			np = nv_open(t->for_.fornam, shp->var_tree,NV_NOASSIGN|NV_NOARRAY|NV_VARNAME|NV_NOREF);
 			nameref = nv_isref(np)!=0;
 			shp->st.loopcnt++;
@@ -2253,10 +2256,11 @@ int sh_exec(register const Shnode_t *t, int flags)
 				shp->exitval=0; /* force zero exit for if-then-fi */
 			break;
 
-		    case TSW:
+		    case TSW:  /* case ... in */
 		    {
 			Shnode_t *tt = (Shnode_t*)t;
 			char *trap, *r = sh_macpat(shp,tt->sw.swarg,OPTIMIZE);
+			shp->exitval = 0;
 			error_info.line = t->sw.swline-shp->st.firstline;
 			t= (Shnode_t*)(tt->sw.swlst);
 			if(trap=shp->st.trap[SH_DEBUGTRAP])
```

**Comment by McDutchie** [comment] 2020-09-09 02:15
For similar reasons as for `TCOM`, unconditionally resetting the exit status for a `TFORK` is also problematic. A similar test case (which also works on every other shell) fails if we involve a background job:

```sh
foo() { return; }
false
foo & wait "$!" && echo "'return' within function does not preserve exit status (bg job)"
```

However, with the fix for `TCOM` above, we don't need that anymore at all (since every background job runs at least one command), so we can simply remove the change for `TFORK`. Diff above updated.

**Comment by McDutchie** [comment] 2020-09-09 02:27
Regression tests:
```sh
foo() { return; }
false
foo && err_exit "'return' within function does not preserve exit status"
false
foo & wait "$!" && err_exit "'return' within function does not preserve exit status (bg job)"

foo() { false; return || :; }
foo && err_exit "'return ||' does not preserve exit status"

foo() { false; return && :; }
foo && err_exit "'return &&' does not preserve exit status"

foo() { false; while return; do true; done; }
foo && err_exit "'while return' does not preserve exit status"

foo() { false; while return; do true; done 2>&1; }
foo && err_exit "'while return' with redirection does not preserve exit status"

foo() { false; until return; do true; done; }
foo && err_exit "'until return' does not preserve exit status"

foo() { false; until return; do true; done 2>&1; }
foo && err_exit "'until return' with redirection does not preserve exit status"

foo() { false; for i in 1; do return; done; }
foo && err_exit "'return' within 'for' does not preserve exit status"

foo() { false; for i in 1; do return; done 2>&1; }
foo && err_exit "'return' within 'for' with redirection does not preserve exit status"

foo() { false; { return; } 2>&1; }
foo && err_exit "'return' within { block; } with redirection does not preserve exit status"

false
for i in; do :; done || err_exit "empty loop does not reset exit status"

false
case 1 in 1) ;; esac || err_exit "empty case does not reset exit status"

false
case 1 in 2) echo whoa ;; esac || err_exit "non-matching case does not reset exit status"
```

**Comment by McDutchie** [comment] 2020-09-09 02:35
The `TCOM` fix is still wrong... sigh.
```
test basic begins at 2020-09-09+04:30:51
	basic.sh[423]: x=$(false) should fail
	basic.sh[424]: $(false) should fail
	basic.sh[423]: x=$(/usr/bin/false) should fail
	basic.sh[424]: $(/usr/bin/false) should fail
test basic failed at 2020-09-09+04:30:57 with exit code 4 [ 105 tests 4 errors ]
```
Of course; there is only an assignment. The command substitution is neither here nor there as that has already been processed and removed by the time we arrive at `TCOM` for the assignment.

There are lots of other regress test failures with that diff as well, some of which I don't understand.

Maybe restoring `oldexit` for specific cases as in https://github.com/ksh93/ksh/issues/117#issuecomment-689224599 is the best way after all.

I'm going to need to sleep on this before trying other things.

**Comment by McDutchie** [comment] 2020-09-09 16:34
Well, so much for all that – the `exitval` handling in xec.c has nothing to do with anything! All we need to fix everything is this one simple change:
```diff
diff --git a/src/cmd/ksh93/bltins/cflow.c b/src/cmd/ksh93/bltins/cflow.c
index 9396de7..34a3e0f 100644
--- a/src/cmd/ksh93/bltins/cflow.c
+++ b/src/cmd/ksh93/bltins/cflow.c
@@ -64,7 +64,7 @@ done:
                errormsg(SH_DICT,ERROR_usage(2),"%s",optusage((char*)0));
        pp->mode = (**argv=='e'?SH_JMPEXIT:SH_JMPFUN);
        argv += opt_info.index;
-       n = (((arg= *argv)?(int)strtol(arg, (char**)0, 10):shp->oldexit));
+       n = (arg = *argv) ? (int)strtol(arg, (char**)0, 10) : shp->savexit;
        if(n<0 || n==256 || n > SH_EXITMASK+shp->gd->sigmax+1)
                        n &= ((unsigned int)n)&SH_EXITMASK;
        /* return outside of function, dotscript and profile is exit */
```
The `return` and `exit` commands are specified to default to "the exit status of the last command executed", which is the `$?` special parameter, when given no argument. And [`$?` uses `savexit`, not `oldexit`](https://github.com/ksh93/ksh/blob/400c107773bc18833385c8fc6aa10f1a66d56e99/src/cmd/ksh93/sh/macro.c#L2777-L2778). So all we need to do is make it default to the correct variable.

After that change, there are no regression test failures – not in `bin/shtests`, not in the new regress tests above, not in the modernish tests (which now no longer detect `BUG_LOOPRET2`).

Also, this turns out to be the only thing that the `sh.oldexit` (== `shp->oldexit`) struct member was used for, so we can get rid of it altogether. What it was supposed to be good for, I've no idea. It seems to be the same thing as `savexit`/`$?`, except slightly broken.

**Closed as completed** 2020-09-09 18:08 UTC
Labels: bug

**Comment by McDutchie** [comment] 2024-01-24 21:33
For the historical record: this fix was wrong because `sh.oldexit` was meant to save the exit status for trap handlers. See aea991588b93b92234c4c9dd0467614c502f9b91.
